/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.catalogue.db;


import com.provys.ealoader.catalogue.db.tables.CatAttrVw;
import com.provys.ealoader.catalogue.db.tables.CatDomainVw;
import com.provys.ealoader.catalogue.db.tables.CatEntityVw;
import com.provys.ealoader.catalogue.db.tables.CatEntitygrpVw;
import com.provys.ealoader.catalogue.db.tables.CatRelVw;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in CAT
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Generated view for entity ATTR
Attribute (catalogue)
     */
    public static final CatAttrVw CAT_ATTR_VW = com.provys.ealoader.catalogue.db.tables.CatAttrVw.CAT_ATTR_VW;

    /**
     * Generated view for entity DOMAIN
Domain - attribute type (catalogue)
     */
    public static final CatDomainVw CAT_DOMAIN_VW = com.provys.ealoader.catalogue.db.tables.CatDomainVw.CAT_DOMAIN_VW;

    /**
     * Generated view for entity ENTITYGRP
Entity group
     */
    public static final CatEntitygrpVw CAT_ENTITYGRP_VW = com.provys.ealoader.catalogue.db.tables.CatEntitygrpVw.CAT_ENTITYGRP_VW;

    /**
     * Generated view for entity ENTITY
Entities (catalogue)
     */
    public static final CatEntityVw CAT_ENTITY_VW = com.provys.ealoader.catalogue.db.tables.CatEntityVw.CAT_ENTITY_VW;

    /**
     * Generated view for entity REL
Relations (catalogue)
     */
    public static final CatRelVw CAT_REL_VW = com.provys.ealoader.catalogue.db.tables.CatRelVw.CAT_REL_VW;
}
