/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.catalogue.db.tables.records;


import com.provys.ealoader.catalogue.db.tables.CatAttrVw;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * Generated view for entity ATTR
 * Attribute (catalogue)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatAttrVwRecord extends TableRecordImpl<CatAttrVwRecord> {

    private static final long serialVersionUID = -1048778405;

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.MANDATORY</code>. Marks mandatory attribute; only valid for columns (attribute type=C) and only affects way entity's PG package is generated.
     */
    public void setMandatory(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.MANDATORY</code>. Marks mandatory attribute; only valid for columns (attribute type=C) and only affects way entity's PG package is generated.
     */
    public String getMandatory() {
        return (String) get(0);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ORDERED</code>. This column represents order (either globally or within children of one parent - see Ordering Group attribute).
     */
    public void setOrdered(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ORDERED</code>. This column represents order (either globally or within children of one parent - see Ordering Group attribute).
     */
    public String getOrdered() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ORDGROUP</code>. Parent attribute (or comma delimited list of parent attributes). Only used when ordered is set to Y - this column is then treated as ordering within group, made by same values of parent attributes
     */
    public void setOrdgroup(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ORDGROUP</code>. Parent attribute (or comma delimited list of parent attributes). Only used when ordered is set to Y - this column is then treated as ordering within group, made by same values of parent attributes
     */
    public String getOrdgroup() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.DEFVALUE</code>. Default value. Only used in generator, should not be changed on installations and is only valid for C (column) attributes.
     */
    public void setDefvalue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.DEFVALUE</code>. Default value. Only used in generator, should not be changed on installations and is only valid for C (column) attributes.
     */
    public String getDefvalue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.MULTICREATE</code>. Create function accepts multiline in this attribute. Only valid for (C)olumn type attributes with domains UID and REF
     */
    public void setMulticreate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.MULTICREATE</code>. Create function accepts multiline in this attribute. Only valid for (C)olumn type attributes with domains UID and REF
     */
    public String getMulticreate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.GENCOPY</code>. Generate mp_Copy_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public void setGencopy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.GENCOPY</code>. Generate mp_Copy_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public String getGencopy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.GENMOVE</code>. Generate mp_Move_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public void setGenmove(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.GENMOVE</code>. Generate mp_Move_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public String getGenmove() {
        return (String) get(6);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.GENDELETE</code>. Generate mp_Delete_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public void setGendelete(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.GENDELETE</code>. Generate mp_Delete_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public String getGendelete() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.TEXTSRC_ID</code>. Source attribute for translated attribute (only for translated attributes)
     */
    public void setTextsrcId(BigInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.TEXTSRC_ID</code>. Source attribute for translated attribute (only for translated attributes)
     */
    public BigInteger getTextsrcId() {
        return (BigInteger) get(8);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.HIERARCHICAL</code>.
     */
    public void setHierarchical(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.HIERARCHICAL</code>.
     */
    public String getHierarchical() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ISINTABLE</code>. Attribute is implemented in table of this Entity
     */
    public void setIsintable(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ISINTABLE</code>. Attribute is implemented in table of this Entity
     */
    public String getIsintable() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ISOWN</code>. Attribute is not inherited
     */
    public void setIsown(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ISOWN</code>. Attribute is not inherited
     */
    public String getIsown() {
        return (String) get(11);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.VALIDATED</code>. Specifies if validation is supported for given attribute. Is used by client to determine if editation in validate edit should be allowed when this attribute is used as format, or if seelction through LOV is required.
     */
    public void setValidated(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.VALIDATED</code>. Specifies if validation is supported for given attribute. Is used by client to determine if editation in validate edit should be allowed when this attribute is used as format, or if seelction through LOV is required.
     */
    public String getValidated() {
        return (String) get(12);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ATTR_ID</code>.
     */
    public void setAttrId(BigInteger value) {
        set(13, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ATTR_ID</code>.
     */
    public BigInteger getAttrId() {
        return (BigInteger) get(13);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ENTITY_ID</code>. UID of entity attribute belongs to
     */
    public void setEntityId(BigInteger value) {
        set(14, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ENTITY_ID</code>. UID of entity attribute belongs to
     */
    public BigInteger getEntityId() {
        return (BigInteger) get(14);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.NAME_NM</code>. Internal name of attribute (name of column / textcolumn in database); also default for shortname
     */
    public void setNameNm(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.NAME_NM</code>. Internal name of attribute (name of column / textcolumn in database); also default for shortname
     */
    public String getNameNm() {
        return (String) get(15);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.NAME</code>. Name of attribute
     */
    public void setName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.NAME</code>. Name of attribute
     */
    public String getName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.NOTE</code>. Note; initialized from comment on given column for "C" and "T" attributes
     */
    public void setNote(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.NOTE</code>. Note; initialized from comment on given column for "C" and "T" attributes
     */
    public String getNote() {
        return (String) get(17);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ATTRTYPE</code>. Type of attribute (C=column, T=text column, F=free attribute, I=financial attribute, Q=free SQL, O=formula)
     */
    public void setAttrtype(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ATTRTYPE</code>. Type of attribute (C=column, T=text column, F=free attribute, I=financial attribute, Q=free SQL, O=formula)
     */
    public String getAttrtype() {
        return (String) get(18);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ISCUSTOM</code>. Custom for instalation
     */
    public void setIscustom(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ISCUSTOM</code>. Custom for instalation
     */
    public String getIscustom() {
        return (String) get(19);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ISUSED</code>. Used on installation
     */
    public void setIsused(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ISUSED</code>. Used on installation
     */
    public String getIsused() {
        return (String) get(20);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ATTRGRP_ID</code>. Attribute group attribute belongs to; used for grouping free or financial attributes on client
     */
    public void setAttrgrpId(BigInteger value) {
        set(21, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ATTRGRP_ID</code>. Attribute group attribute belongs to; used for grouping free or financial attributes on client
     */
    public BigInteger getAttrgrpId() {
        return (BigInteger) get(21);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ORD</code>. Ordering of attributes within group; attributes with same ORD are usually ordered using name
Ordering is used for generate
     */
    public void setOrd(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ORD</code>. Ordering of attributes within group; attributes with same ORD are usually ordered using name
Ordering is used for generate
     */
    public Integer getOrd() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.DOMAIN_ID</code>. Domain
     */
    public void setDomainId(BigInteger value) {
        set(23, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.DOMAIN_ID</code>. Domain
     */
    public BigInteger getDomainId() {
        return (BigInteger) get(23);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.SUBDOMAIN_NM</code>. Subdomain - closer specification of domain
     */
    public void setSubdomainNm(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.SUBDOMAIN_NM</code>. Subdomain - closer specification of domain
     */
    public String getSubdomainNm() {
        return (String) get(24);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.QVISIBLE</code>. Attribute is visible to users by default; setting can be overriden on profile level (see attribute profile settings).
     */
    public void setQvisible(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.QVISIBLE</code>. Attribute is visible to users by default; setting can be overriden on profile level (see attribute profile settings).
     */
    public String getQvisible() {
        return (String) get(25);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.LLENGTH</code>. Default length of atribute in lists
     */
    public void setLlength(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.LLENGTH</code>. Default length of atribute in lists
     */
    public Integer getLlength() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.INDEXED</code>. Column is indexed; only usable for "C" attributes
     */
    public void setIndexed(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.INDEXED</code>. Column is indexed; only usable for "C" attributes
     */
    public String getIndexed() {
        return (String) get(27);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.UPNAME_NM</code>. Name of upper-cased column; only usable for "C" or "T" attributes
     */
    public void setUpnameNm(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.UPNAME_NM</code>. Name of upper-cased column; only usable for "C" or "T" attributes
     */
    public String getUpnameNm() {
        return (String) get(28);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.READONLY</code>. Value of attribute cannot be (directly) set by user.
- for columns and text (translated) attributes this has to be N, no checking is performed
- for formulas and SQL attributes, this has to be Y as it is never possible to modify their values
- for financial attributes, it is not possible to set value (or even define accounting rule for change of value) if attribute is read-only; value should be changed either through other financial attribute or by creating accounting records using other methods (through planned operations or some interface). If it is not read-only, accounting rule must be defined
- for free attributes, if free attribute is marked as read-only, user cannot change its value directly, it is only possible to change it using PG version of mp_Set with p_ChangeReadOnly=TRUE. It can be used for attributes which are replicated from other system or set through CP interface of some entity
     */
    public void setReadonly(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.READONLY</code>. Value of attribute cannot be (directly) set by user.
- for columns and text (translated) attributes this has to be N, no checking is performed
- for formulas and SQL attributes, this has to be Y as it is never possible to modify their values
- for financial attributes, it is not possible to set value (or even define accounting rule for change of value) if attribute is read-only; value should be changed either through other financial attribute or by creating accounting records using other methods (through planned operations or some interface). If it is not read-only, accounting rule must be defined
- for free attributes, if free attribute is marked as read-only, user cannot change its value directly, it is only possible to change it using PG version of mp_Set with p_ChangeReadOnly=TRUE. It can be used for attributes which are replicated from other system or set through CP interface of some entity
     */
    public String getReadonly() {
        return (String) get(29);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.GETOPTYPE_ID</code>. Operation type tested when accessing value of attribute
     */
    public void setGetoptypeId(BigInteger value) {
        set(30, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.GETOPTYPE_ID</code>. Operation type tested when accessing value of attribute
     */
    public BigInteger getGetoptypeId() {
        return (BigInteger) get(30);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.SETOPTYPE_ID</code>. Operation type tested when changing value of attribute
     */
    public void setSetoptypeId(BigInteger value) {
        set(31, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.SETOPTYPE_ID</code>. Operation type tested when changing value of attribute
     */
    public BigInteger getSetoptypeId() {
        return (BigInteger) get(31);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.RESETOPTYPE_ID</code>. Operation type tested when changing value of attribute to NULL; if not specified, SETOPTYPE_ID is used instead
     */
    public void setResetoptypeId(BigInteger value) {
        set(32, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.RESETOPTYPE_ID</code>. Operation type tested when changing value of attribute to NULL; if not specified, SETOPTYPE_ID is used instead
     */
    public BigInteger getResetoptypeId() {
        return (BigInteger) get(32);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.CONFIRMOTHER</code>. Used for confirmation attributes; value of N means that user cannot set who confirmed action
     */
    public void setConfirmother(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.CONFIRMOTHER</code>. Used for confirmation attributes; value of N means that user cannot set who confirmed action
     */
    public String getConfirmother() {
        return (String) get(33);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.SETOTHEROPTYPE_ID</code>. Operation type tested when changing value of CONFIRM attribute to person other than logged-in user; NULL means same rules apply as for SETOPTYPE_ID
     */
    public void setSetotheroptypeId(BigInteger value) {
        set(34, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.SETOTHEROPTYPE_ID</code>. Operation type tested when changing value of CONFIRM attribute to person other than logged-in user; NULL means same rules apply as for SETOPTYPE_ID
     */
    public BigInteger getSetotheroptypeId() {
        return (BigInteger) get(34);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.MULTIVALUE</code>. Multivalue allowed; valid only for free attributes
     */
    public void setMultivalue(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.MULTIVALUE</code>. Multivalue allowed; valid only for free attributes
     */
    public String getMultivalue() {
        return (String) get(35);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.LOGALLOWED</code>. Logging/dictionary indexing is supported
     */
    public void setLogallowed(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.LOGALLOWED</code>. Logging/dictionary indexing is supported
     */
    public String getLogallowed() {
        return (String) get(36);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.LOGLEVEL</code>. Log level (N=none, C=current value, H=changes log(history))
     */
    public void setLoglevel(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.LOGLEVEL</code>. Log level (N=none, C=current value, H=changes log(history))
     */
    public String getLoglevel() {
        return (String) get(37);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.DICTTYPE</code>. Type of storage of attribute in dictionary
     */
    public void setDicttype(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.DICTTYPE</code>. Type of storage of attribute in dictionary
     */
    public String getDicttype() {
        return (String) get(38);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.DICTDEL1</code>. Terms delimiter
     */
    public void setDictdel1(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.DICTDEL1</code>. Terms delimiter
     */
    public String getDictdel1() {
        return (String) get(39);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.DICTDEL2</code>. Terms delimiter
     */
    public void setDictdel2(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.DICTDEL2</code>. Terms delimiter
     */
    public String getDictdel2() {
        return (String) get(40);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.TBCODE_CD</code>. Code used to evaluate attribute value (when used internally); for "X" and "O" atributes
     */
    public void setTbcodeCd(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.TBCODE_CD</code>. Code used to evaluate attribute value (when used internally); for "X" and "O" atributes
     */
    public String getTbcodeCd() {
        return (String) get(41);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ACCOUNTRULE_NM</code>. Internal name of an accounting rule to be used to book the value for object (only for financial attributes)
     */
    public void setAccountruleNm(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ACCOUNTRULE_NM</code>. Internal name of an accounting rule to be used to book the value for object (only for financial attributes)
     */
    public String getAccountruleNm() {
        return (String) get(42);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.ACCDOCOBJECTFORMULA_ID</code>. Accounting document, created when changing value of this financial attribute will be connected to object, evaluated using this attribute. When left blank, document will be connected to object on which action was called (only for financial attributes)
     */
    public void setAccdocobjectformulaId(BigInteger value) {
        set(43, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.ACCDOCOBJECTFORMULA_ID</code>. Accounting document, created when changing value of this financial attribute will be connected to object, evaluated using this attribute. When left blank, document will be connected to object on which action was called (only for financial attributes)
     */
    public BigInteger getAccdocobjectformulaId() {
        return (BigInteger) get(43);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.OWNERFORMULA_ID</code>. Owner of ledger used to evaluate value of financial attribute.
     */
    public void setOwnerformulaId(BigInteger value) {
        set(44, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.OWNERFORMULA_ID</code>. Owner of ledger used to evaluate value of financial attribute.
     */
    public BigInteger getOwnerformulaId() {
        return (BigInteger) get(44);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.FROMOBJECTFORMULA_ID</code>. Used when value of financial attribute is changed - value of this attribute is object to be used on spent side of accounting record
     */
    public void setFromobjectformulaId(BigInteger value) {
        set(45, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.FROMOBJECTFORMULA_ID</code>. Used when value of financial attribute is changed - value of this attribute is object to be used on spent side of accounting record
     */
    public BigInteger getFromobjectformulaId() {
        return (BigInteger) get(45);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.TOOBJECTFORMULA_ID</code>. Used when value of financial attribute is changed - value of this attribute is object to be used on received side of accounting record
     */
    public void setToobjectformulaId(BigInteger value) {
        set(46, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.TOOBJECTFORMULA_ID</code>. Used when value of financial attribute is changed - value of this attribute is object to be used on received side of accounting record
     */
    public BigInteger getToobjectformulaId() {
        return (BigInteger) get(46);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.APPROXRECORD</code>. Indicates if the created accounting record will be approximate (only for financial attributes)
     */
    public void setApproxrecord(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.APPROXRECORD</code>. Indicates if the created accounting record will be approximate (only for financial attributes)
     */
    public String getApproxrecord() {
        return (String) get(47);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.VALUEACCOUNT_NM</code>. Short name of account to read actual value (only for financial attributes)
     */
    public void setValueaccountNm(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.VALUEACCOUNT_NM</code>. Short name of account to read actual value (only for financial attributes)
     */
    public String getValueaccountNm() {
        return (String) get(48);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.VALUEAMOUNTTYPE</code>. R(eceived), S(pent), T(otal) amount of the balance to read actual value (only for financial attributes)
     */
    public void setValueamounttype(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.VALUEAMOUNTTYPE</code>. R(eceived), S(pent), T(otal) amount of the balance to read actual value (only for financial attributes)
     */
    public String getValueamounttype() {
        return (String) get(49);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.DEFOWNER</code>. Default owner points to unit that acts as owner of given object for purpose of accounting
     */
    public void setDefowner(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.DEFOWNER</code>. Default owner points to unit that acts as owner of given object for purpose of accounting
     */
    public String getDefowner() {
        return (String) get(50);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.DOCUMENTATION</code>. Addional documentation related to the attribute (not generated to the table column comment)
     */
    public void setDocumentation(String value) {
        set(51, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.DOCUMENTATION</code>. Addional documentation related to the attribute (not generated to the table column comment)
     */
    public String getDocumentation() {
        return (String) get(51);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.BITMAPORD</code>. Order in Attribute Set Bitmap, 0=Least Significant bit. Used internally in generated parts of PG packages (only for column attributes)
     */
    public void setBitmapord(Integer value) {
        set(52, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.BITMAPORD</code>. Order in Attribute Set Bitmap, 0=Least Significant bit. Used internally in generated parts of PG packages (only for column attributes)
     */
    public Integer getBitmapord() {
        return (Integer) get(52);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.X_ISFLAGDEPBIND</code>.
     */
    public void setXIsflagdepbind(String value) {
        set(53, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.X_ISFLAGDEPBIND</code>.
     */
    public String getXIsflagdepbind() {
        return (String) get(53);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.X_ISFLAGDEFATTR</code>. Shows if Attribute is used in any Flag Definition (via. FlagDefAttr, or DstAttr of any FlagDep)
     */
    public void setXIsflagdefattr(String value) {
        set(54, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.X_ISFLAGDEFATTR</code>. Shows if Attribute is used in any Flag Definition (via. FlagDefAttr, or DstAttr of any FlagDep)
     */
    public String getXIsflagdefattr() {
        return (String) get(54);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.COPIED</code>. Attribute value is copied in copy operations.
     */
    public void setCopied(String value) {
        set(55, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.COPIED</code>. Attribute value is copied in copy operations.
     */
    public String getCopied() {
        return (String) get(55);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.KEYORD</code>. Order of given attribute in key of given entity
     */
    public void setKeyord(Integer value) {
        set(56, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.KEYORD</code>. Order of given attribute in key of given entity
     */
    public Integer getKeyord() {
        return (Integer) get(56);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.OPTYPETYPE_RF</code>. Specifies type of operation for UID / operation type attributes that support automatic optype creation
     */
    public void setOptypetypeRf(BigInteger value) {
        set(57, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.OPTYPETYPE_RF</code>. Specifies type of operation for UID / operation type attributes that support automatic optype creation
     */
    public BigInteger getOptypetypeRf() {
        return (BigInteger) get(57);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.IMGSRC_ID</code>. Reference to the image souce, which we should resize
     */
    public void setImgsrcId(BigInteger value) {
        set(58, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.IMGSRC_ID</code>. Reference to the image souce, which we should resize
     */
    public BigInteger getImgsrcId() {
        return (BigInteger) get(58);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.IMGWIDTH</code>. The width of the picture to resize
     */
    public void setImgwidth(Integer value) {
        set(59, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.IMGWIDTH</code>. The width of the picture to resize
     */
    public Integer getImgwidth() {
        return (Integer) get(59);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.IMGHEIGHT</code>. The height of the picture to resize
     */
    public void setImgheight(Integer value) {
        set(60, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.IMGHEIGHT</code>. The height of the picture to resize
     */
    public Integer getImgheight() {
        return (Integer) get(60);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.FILESERVER_ID</code>. [KO150414-21B7CDA] Ukladani souboru mimo databazi
     */
    public void setFileserverId(BigInteger value) {
        set(61, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.FILESERVER_ID</code>. [KO150414-21B7CDA] Ukladani souboru mimo databazi
     */
    public BigInteger getFileserverId() {
        return (BigInteger) get(61);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.GENMIGR</code>. Used for generator of migration framework
     */
    public void setGenmigr(String value) {
        set(62, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.GENMIGR</code>. Used for generator of migration framework
     */
    public String getGenmigr() {
        return (String) get(62);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.EVALCVALUE</code>. Evaluate and store text from binary document. Text representation can be used in fulltext searches - thus, it should be enabled for properties, that are included in fulltext search flagdef. Is always empty for domains other than BLOB
     */
    public void setEvalcvalue(String value) {
        set(63, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.EVALCVALUE</code>. Evaluate and store text from binary document. Text representation can be used in fulltext searches - thus, it should be enabled for properties, that are included in fulltext search flagdef. Is always empty for domains other than BLOB
     */
    public String getEvalcvalue() {
        return (String) get(63);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.OPTLOBLIMIT</code>. Optional limit for length of lob free atribut. It show alert.  The limit  is in bytes
     */
    public void setOptloblimit(BigDecimal value) {
        set(64, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.OPTLOBLIMIT</code>. Optional limit for length of lob free atribut. It show alert.  The limit  is in bytes
     */
    public BigDecimal getOptloblimit() {
        return (BigDecimal) get(64);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.MANLOBLIMIT</code>. Mandatory limit for length of lob free atribute. It show error. The limit is in bytes.
     */
    public void setManloblimit(BigDecimal value) {
        set(65, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.MANLOBLIMIT</code>. Mandatory limit for length of lob free atribute. It show error. The limit is in bytes.
     */
    public BigDecimal getManloblimit() {
        return (BigDecimal) get(65);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_ISACTIVE</code>. Whether attribute or any of its ancestors has Is Own flag set
     */
    public void setCIsactive(String value) {
        set(66, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_ISACTIVE</code>. Whether attribute or any of its ancestors has Is Own flag set
     */
    public String getCIsactive() {
        return (String) get(66);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.NLSSHORT</code>. Shortname
     */
    public void setNlsshort(String value) {
        set(67, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.NLSSHORT</code>. Shortname
     */
    public String getNlsshort() {
        return (String) get(67);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.NLSNAME</code>. Name
     */
    public void setNlsname(String value) {
        set(68, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.NLSNAME</code>. Name
     */
    public String getNlsname() {
        return (String) get(68);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_ANCESTOR_ID</code>. Ancestor is attribute in entity ancestor with same internal name.
     */
    public void setCAncestorId(BigDecimal value) {
        set(69, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_ANCESTOR_ID</code>. Ancestor is attribute in entity ancestor with same internal name.
     */
    public BigDecimal getCAncestorId() {
        return (BigDecimal) get(69);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_DOCUMENTATION</code>. Documentation, potentially inherited from attribute's ancestor
     */
    public void setCDocumentation(String value) {
        set(70, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_DOCUMENTATION</code>. Documentation, potentially inherited from attribute's ancestor
     */
    public String getCDocumentation() {
        return (String) get(70);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_ENTITY_NM</code>.
     */
    public void setCEntityNm(String value) {
        set(71, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_ENTITY_NM</code>.
     */
    public String getCEntityNm() {
        return (String) get(71);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_GETOPTYPEAUTO</code>.
     */
    public void setCGetoptypeauto(String value) {
        set(72, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_GETOPTYPEAUTO</code>.
     */
    public String getCGetoptypeauto() {
        return (String) get(72);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_NOTE</code>. Note, potentially inherited from attribute's ancestor
     */
    public void setCNote(String value) {
        set(73, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_NOTE</code>. Note, potentially inherited from attribute's ancestor
     */
    public String getCNote() {
        return (String) get(73);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_OWNERFORMULA_ID</code>. Effective value of attribute, used to evaluate owner of object (and thus ledger) to be used with given financial attribute.
     */
    public void setCOwnerformulaId(BigDecimal value) {
        set(74, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_OWNERFORMULA_ID</code>. Effective value of attribute, used to evaluate owner of object (and thus ledger) to be used with given financial attribute.
     */
    public BigDecimal getCOwnerformulaId() {
        return (BigDecimal) get(74);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_RESETOPTYPEAUTO</code>.
     */
    public void setCResetoptypeauto(String value) {
        set(75, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_RESETOPTYPEAUTO</code>.
     */
    public String getCResetoptypeauto() {
        return (String) get(75);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_SETOPTYPEAUTO</code>.
     */
    public void setCSetoptypeauto(String value) {
        set(76, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_SETOPTYPEAUTO</code>.
     */
    public String getCSetoptypeauto() {
        return (String) get(76);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.C_SETOTHEROPTYPEAUTO</code>.
     */
    public void setCSetotheroptypeauto(String value) {
        set(77, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.C_SETOTHEROPTYPEAUTO</code>.
     */
    public String getCSetotheroptypeauto() {
        return (String) get(77);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.I_DOCUMENTATION</code>. Description in attribute's ancestor
     */
    public void setIDocumentation(String value) {
        set(78, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.I_DOCUMENTATION</code>. Description in attribute's ancestor
     */
    public String getIDocumentation() {
        return (String) get(78);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.I_NOTE</code>. Note in attribute's ancestor
     */
    public void setINote(String value) {
        set(79, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.I_NOTE</code>. Note in attribute's ancestor
     */
    public String getINote() {
        return (String) get(79);
    }

    /**
     * Setter for <code>CAT.CAT_ATTR_VW.NLSNOTE</code>. Note
     */
    public void setNlsnote(String value) {
        set(80, value);
    }

    /**
     * Getter for <code>CAT.CAT_ATTR_VW.NLSNOTE</code>. Note
     */
    public String getNlsnote() {
        return (String) get(80);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CatAttrVwRecord
     */
    public CatAttrVwRecord() {
        super(CatAttrVw.CAT_ATTR_VW);
    }

    /**
     * Create a detached, initialised CatAttrVwRecord
     */
    public CatAttrVwRecord(String mandatory, String ordered, String ordgroup, String defvalue, String multicreate, String gencopy, String genmove, String gendelete, BigInteger textsrcId, String hierarchical, String isintable, String isown, String validated, BigInteger attrId, BigInteger entityId, String nameNm, String name, String note, String attrtype, String iscustom, String isused, BigInteger attrgrpId, Integer ord, BigInteger domainId, String subdomainNm, String qvisible, Integer llength, String indexed, String upnameNm, String readonly, BigInteger getoptypeId, BigInteger setoptypeId, BigInteger resetoptypeId, String confirmother, BigInteger setotheroptypeId, String multivalue, String logallowed, String loglevel, String dicttype, String dictdel1, String dictdel2, String tbcodeCd, String accountruleNm, BigInteger accdocobjectformulaId, BigInteger ownerformulaId, BigInteger fromobjectformulaId, BigInteger toobjectformulaId, String approxrecord, String valueaccountNm, String valueamounttype, String defowner, String documentation, Integer bitmapord, String xIsflagdepbind, String xIsflagdefattr, String copied, Integer keyord, BigInteger optypetypeRf, BigInteger imgsrcId, Integer imgwidth, Integer imgheight, BigInteger fileserverId, String genmigr, String evalcvalue, BigDecimal optloblimit, BigDecimal manloblimit, String cIsactive, String nlsshort, String nlsname, BigDecimal cAncestorId, String cDocumentation, String cEntityNm, String cGetoptypeauto, String cNote, BigDecimal cOwnerformulaId, String cResetoptypeauto, String cSetoptypeauto, String cSetotheroptypeauto, String iDocumentation, String iNote, String nlsnote) {
        super(CatAttrVw.CAT_ATTR_VW);

        set(0, mandatory);
        set(1, ordered);
        set(2, ordgroup);
        set(3, defvalue);
        set(4, multicreate);
        set(5, gencopy);
        set(6, genmove);
        set(7, gendelete);
        set(8, textsrcId);
        set(9, hierarchical);
        set(10, isintable);
        set(11, isown);
        set(12, validated);
        set(13, attrId);
        set(14, entityId);
        set(15, nameNm);
        set(16, name);
        set(17, note);
        set(18, attrtype);
        set(19, iscustom);
        set(20, isused);
        set(21, attrgrpId);
        set(22, ord);
        set(23, domainId);
        set(24, subdomainNm);
        set(25, qvisible);
        set(26, llength);
        set(27, indexed);
        set(28, upnameNm);
        set(29, readonly);
        set(30, getoptypeId);
        set(31, setoptypeId);
        set(32, resetoptypeId);
        set(33, confirmother);
        set(34, setotheroptypeId);
        set(35, multivalue);
        set(36, logallowed);
        set(37, loglevel);
        set(38, dicttype);
        set(39, dictdel1);
        set(40, dictdel2);
        set(41, tbcodeCd);
        set(42, accountruleNm);
        set(43, accdocobjectformulaId);
        set(44, ownerformulaId);
        set(45, fromobjectformulaId);
        set(46, toobjectformulaId);
        set(47, approxrecord);
        set(48, valueaccountNm);
        set(49, valueamounttype);
        set(50, defowner);
        set(51, documentation);
        set(52, bitmapord);
        set(53, xIsflagdepbind);
        set(54, xIsflagdefattr);
        set(55, copied);
        set(56, keyord);
        set(57, optypetypeRf);
        set(58, imgsrcId);
        set(59, imgwidth);
        set(60, imgheight);
        set(61, fileserverId);
        set(62, genmigr);
        set(63, evalcvalue);
        set(64, optloblimit);
        set(65, manloblimit);
        set(66, cIsactive);
        set(67, nlsshort);
        set(68, nlsname);
        set(69, cAncestorId);
        set(70, cDocumentation);
        set(71, cEntityNm);
        set(72, cGetoptypeauto);
        set(73, cNote);
        set(74, cOwnerformulaId);
        set(75, cResetoptypeauto);
        set(76, cSetoptypeauto);
        set(77, cSetotheroptypeauto);
        set(78, iDocumentation);
        set(79, iNote);
        set(80, nlsnote);
    }
}
