/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.catalogue.db.tables.records;


import com.provys.ealoader.catalogue.db.tables.CatDomainVw;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;


/**
 * Generated view for entity DOMAIN
 * Domain - attribute type (catalogue)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatDomainVwRecord extends TableRecordImpl<CatDomainVwRecord> implements Record14<BigInteger, String, String, String, String, Short, Byte, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1381720165;

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.DOMAIN_ID</code>. UID of domain
     */
    public void setDomainId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.DOMAIN_ID</code>. UID of domain
     */
    public BigInteger getDomainId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.NAME_NM</code>. Internal name of domain
     */
    public void setNameNm(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.NAME_NM</code>. Internal name of domain
     */
    public String getNameNm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.NAME</code>. Name of domain
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.NAME</code>. Name of domain
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.X_UPNAME</code>. Calculated column - uppercase of NAME
     */
    public void setXUpname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.X_UPNAME</code>. Calculated column - uppercase of NAME
     */
    public String getXUpname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.DATATYPE_NM</code>. PROVYS datatype used for implementation of column of this domain
     */
    public void setDatatypeNm(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.DATATYPE_NM</code>. PROVYS datatype used for implementation of column of this domain
     */
    public String getDatatypeNm() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.DATALENGTH</code>. Length (maximum length) of data column corresponding to this domain
     */
    public void setDatalength(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.DATALENGTH</code>. Length (maximum length) of data column corresponding to this domain
     */
    public Short getDatalength() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.DATAPRECISION</code>. Precision of columns from this domain (for numbers only)
     */
    public void setDataprecision(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.DATAPRECISION</code>. Precision of columns from this domain (for numbers only)
     */
    public Byte getDataprecision() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.NOTE</code>. Notes for administrator of catalogue
     */
    public void setNote(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.NOTE</code>. Notes for administrator of catalogue
     */
    public String getNote() {
        return (String) get(7);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.ALLOWED</code>. Not allowed domains cannot be manualy created and they are reported in servercheck. Items (e.g. attributes or components) with non-allowed domains should be changed to allowed ones.
     */
    public void setAllowed(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.ALLOWED</code>. Not allowed domains cannot be manualy created and they are reported in servercheck. Items (e.g. attributes or components) with non-allowed domains should be changed to allowed ones.
     */
    public String getAllowed() {
        return (String) get(8);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.QVISIBLE</code>. Default query visibility for columns from this domain
     */
    public void setQvisible(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.QVISIBLE</code>. Default query visibility for columns from this domain
     */
    public String getQvisible() {
        return (String) get(9);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.LVISIBLE</code>. Default lists visibility for columns from this domain
     */
    public void setLvisible(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.LVISIBLE</code>. Default lists visibility for columns from this domain
     */
    public String getLvisible() {
        return (String) get(10);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.VALIDATE_CD</code>. PL/SQL block for standard validation (used if no format-specific validation is specified); value should be bound to IN/OUT :c_Value bind variable
     */
    public void setValidateCd(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.VALIDATE_CD</code>. PL/SQL block for standard validation (used if no format-specific validation is specified); value should be bound to IN/OUT :c_Value bind variable
     */
    public String getValidateCd() {
        return (String) get(11);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.LFORMAT_CD</code>. PL/SQL block for creation of formated output in list
     */
    public void setLformatCd(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.LFORMAT_CD</code>. PL/SQL block for creation of formated output in list
     */
    public String getLformatCd() {
        return (String) get(12);
    }

    /**
     * Setter for <code>CAT.CAT_DOMAIN_VW.NATORDER</code>. When domain has native ordering, unmodified attribute value is used for ordering in XML lists. For domains without native ordering, formatted value (converted to string) is used
     */
    public void setNatorder(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>CAT.CAT_DOMAIN_VW.NATORDER</code>. When domain has native ordering, unmodified attribute value is used for ordering in XML lists. For domains without native ordering, formatted value (converted to string) is used
     */
    public String getNatorder() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<BigInteger, String, String, String, String, Short, Byte, String, String, String, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<BigInteger, String, String, String, String, Short, Byte, String, String, String, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return CatDomainVw.CAT_DOMAIN_VW.DOMAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CatDomainVw.CAT_DOMAIN_VW.NAME_NM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CatDomainVw.CAT_DOMAIN_VW.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CatDomainVw.CAT_DOMAIN_VW.X_UPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CatDomainVw.CAT_DOMAIN_VW.DATATYPE_NM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return CatDomainVw.CAT_DOMAIN_VW.DATALENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return CatDomainVw.CAT_DOMAIN_VW.DATAPRECISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CatDomainVw.CAT_DOMAIN_VW.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CatDomainVw.CAT_DOMAIN_VW.ALLOWED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CatDomainVw.CAT_DOMAIN_VW.QVISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CatDomainVw.CAT_DOMAIN_VW.LVISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return CatDomainVw.CAT_DOMAIN_VW.VALIDATE_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return CatDomainVw.CAT_DOMAIN_VW.LFORMAT_CD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return CatDomainVw.CAT_DOMAIN_VW.NATORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getDomainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNameNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getXUpname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDatatypeNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getDatalength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getDataprecision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getAllowed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getQvisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getLvisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getValidateCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getLformatCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getNatorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getDomainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNameNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getXUpname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDatatypeNm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getDatalength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getDataprecision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAllowed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getQvisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getLvisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getValidateCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getLformatCd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getNatorder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value1(BigInteger value) {
        setDomainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value2(String value) {
        setNameNm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value4(String value) {
        setXUpname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value5(String value) {
        setDatatypeNm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value6(Short value) {
        setDatalength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value7(Byte value) {
        setDataprecision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value8(String value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value9(String value) {
        setAllowed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value10(String value) {
        setQvisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value11(String value) {
        setLvisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value12(String value) {
        setValidateCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value13(String value) {
        setLformatCd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord value14(String value) {
        setNatorder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatDomainVwRecord values(BigInteger value1, String value2, String value3, String value4, String value5, Short value6, Byte value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CatDomainVwRecord
     */
    public CatDomainVwRecord() {
        super(CatDomainVw.CAT_DOMAIN_VW);
    }

    /**
     * Create a detached, initialised CatDomainVwRecord
     */
    public CatDomainVwRecord(BigInteger domainId, String nameNm, String name, String xUpname, String datatypeNm, Short datalength, Byte dataprecision, String note, String allowed, String qvisible, String lvisible, String validateCd, String lformatCd, String natorder) {
        super(CatDomainVw.CAT_DOMAIN_VW);

        set(0, domainId);
        set(1, nameNm);
        set(2, name);
        set(3, xUpname);
        set(4, datatypeNm);
        set(5, datalength);
        set(6, dataprecision);
        set(7, note);
        set(8, allowed);
        set(9, qvisible);
        set(10, lvisible);
        set(11, validateCd);
        set(12, lformatCd);
        set(13, natorder);
    }
}
