/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.catalogue.db.tables;


import com.provys.ealoader.catalogue.db.Indexes;
import com.provys.ealoader.catalogue.db.Ker;
import com.provys.ealoader.catalogue.db.Keys;
import com.provys.ealoader.catalogue.db.tables.records.KerDomainTbRecord;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Domain - attribute type (catalogue)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KerDomainTb extends TableImpl<KerDomainTbRecord> {

    private static final long serialVersionUID = -824561147;

    /**
     * The reference instance of <code>KER.KER_DOMAIN_TB</code>
     */
    public static final KerDomainTb KER_DOMAIN_TB = new KerDomainTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KerDomainTbRecord> getRecordType() {
        return KerDomainTbRecord.class;
    }

    /**
     * The column <code>KER.KER_DOMAIN_TB.DOMAIN_ID</code>. UID of domain
     */
    public final TableField<KerDomainTbRecord, BigInteger> DOMAIN_ID = createField("DOMAIN_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false), this, "UID of domain");

    /**
     * The column <code>KER.KER_DOMAIN_TB.NAME_NM</code>. Internal name of domain
     */
    public final TableField<KerDomainTbRecord, String> NAME_NM = createField("NAME_NM", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "Internal name of domain");

    /**
     * The column <code>KER.KER_DOMAIN_TB.NAME</code>. Name of domain
     */
    public final TableField<KerDomainTbRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "Name of domain");

    /**
     * The column <code>KER.KER_DOMAIN_TB.X_UPNAME</code>. Calculated column - uppercase of NAME
     */
    public final TableField<KerDomainTbRecord, String> X_UPNAME = createField("X_UPNAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "Calculated column - uppercase of NAME");

    /**
     * The column <code>KER.KER_DOMAIN_TB.DATATYPE_NM</code>. PROVYS datatype used for implementation of column of this domain
     */
    public final TableField<KerDomainTbRecord, String> DATATYPE_NM = createField("DATATYPE_NM", org.jooq.impl.SQLDataType.VARCHAR(20), this, "PROVYS datatype used for implementation of column of this domain");

    /**
     * The column <code>KER.KER_DOMAIN_TB.DATALENGTH</code>. Length (maximum length) of data column corresponding to this domain
     */
    public final TableField<KerDomainTbRecord, Short> DATALENGTH = createField("DATALENGTH", org.jooq.impl.SQLDataType.SMALLINT, this, "Length (maximum length) of data column corresponding to this domain");

    /**
     * The column <code>KER.KER_DOMAIN_TB.DATAPRECISION</code>. Precision of columns from this domain (for numbers only)
     */
    public final TableField<KerDomainTbRecord, Byte> DATAPRECISION = createField("DATAPRECISION", org.jooq.impl.SQLDataType.TINYINT, this, "Precision of columns from this domain (for numbers only)");

    /**
     * The column <code>KER.KER_DOMAIN_TB.QVISIBLE</code>. Default query visibility for columns from this domain
     */
    public final TableField<KerDomainTbRecord, String> QVISIBLE = createField("QVISIBLE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'Y' ", org.jooq.impl.SQLDataType.CHAR)), this, "Default query visibility for columns from this domain");

    /**
     * The column <code>KER.KER_DOMAIN_TB.LVISIBLE</code>. Default lists visibility for columns from this domain
     */
    public final TableField<KerDomainTbRecord, String> LVISIBLE = createField("LVISIBLE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'Y' ", org.jooq.impl.SQLDataType.CHAR)), this, "Default lists visibility for columns from this domain");

    /**
     * The column <code>KER.KER_DOMAIN_TB.VALIDATE_CD</code>. PL/SQL block for standard validation (used if no format-specific validation is specified); value should be bound to IN/OUT :c_Value bind variable
     */
    public final TableField<KerDomainTbRecord, String> VALIDATE_CD = createField("VALIDATE_CD", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "PL/SQL block for standard validation (used if no format-specific validation is specified); value should be bound to IN/OUT :c_Value bind variable");

    /**
     * The column <code>KER.KER_DOMAIN_TB.LFORMAT_CD</code>. PL/SQL block for creation of formated output in list
     */
    public final TableField<KerDomainTbRecord, String> LFORMAT_CD = createField("LFORMAT_CD", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "PL/SQL block for creation of formated output in list");

    /**
     * The column <code>KER.KER_DOMAIN_TB.NATORDER</code>. When domain has native ordering, unmodified attribute value is used for ordering in XML lists. For domains without native ordering, formatted value (converted to string) is used
     */
    public final TableField<KerDomainTbRecord, String> NATORDER = createField("NATORDER", org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'Y' ", org.jooq.impl.SQLDataType.CHAR)), this, "When domain has native ordering, unmodified attribute value is used for ordering in XML lists. For domains without native ordering, formatted value (converted to string) is used");

    /**
     * The column <code>KER.KER_DOMAIN_TB.NOTE</code>. Notes for administrator of catalogue
     */
    public final TableField<KerDomainTbRecord, String> NOTE = createField("NOTE", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Notes for administrator of catalogue");

    /**
     * The column <code>KER.KER_DOMAIN_TB.ALLOWED</code>. Not allowed domains cannot be manualy created and they are reported in servercheck. Items (e.g. attributes or components) with non-allowed domains should be changed to allowed ones.
     */
    public final TableField<KerDomainTbRecord, String> ALLOWED = createField("ALLOWED", org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.field("'Y' ", org.jooq.impl.SQLDataType.CHAR)), this, "Not allowed domains cannot be manualy created and they are reported in servercheck. Items (e.g. attributes or components) with non-allowed domains should be changed to allowed ones.");

    /**
     * Create a <code>KER.KER_DOMAIN_TB</code> table reference
     */
    public KerDomainTb() {
        this(DSL.name("KER_DOMAIN_TB"), null);
    }

    /**
     * Create an aliased <code>KER.KER_DOMAIN_TB</code> table reference
     */
    public KerDomainTb(String alias) {
        this(DSL.name(alias), KER_DOMAIN_TB);
    }

    /**
     * Create an aliased <code>KER.KER_DOMAIN_TB</code> table reference
     */
    public KerDomainTb(Name alias) {
        this(alias, KER_DOMAIN_TB);
    }

    private KerDomainTb(Name alias, Table<KerDomainTbRecord> aliased) {
        this(alias, aliased, null);
    }

    private KerDomainTb(Name alias, Table<KerDomainTbRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Domain - attribute type (catalogue)"));
    }

    public <O extends Record> KerDomainTb(Table<O> child, ForeignKey<O, KerDomainTbRecord> key) {
        super(child, key, KER_DOMAIN_TB);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ker.KER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.KER_DOMAIN_NM_IX, Indexes.KER_DOMAIN_PK, Indexes.KER_DOMAIN_UPNAME_IX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<KerDomainTbRecord> getPrimaryKey() {
        return Keys.KER_DOMAIN_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<KerDomainTbRecord>> getKeys() {
        return Arrays.<UniqueKey<KerDomainTbRecord>>asList(Keys.KER_DOMAIN_PK, Keys.KER_DOMAIN_NM_UK, Keys.KER_DOMAIN_UPNAME_UK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerDomainTb as(String alias) {
        return new KerDomainTb(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KerDomainTb as(Name alias) {
        return new KerDomainTb(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public KerDomainTb rename(String name) {
        return new KerDomainTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public KerDomainTb rename(Name name) {
        return new KerDomainTb(name, null);
    }
}
