/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.catalogue.db.tables;


import com.provys.ealoader.catalogue.db.Cat;
import com.provys.ealoader.catalogue.db.tables.records.CatAttrVwRecord;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Generated view for entity ATTR
 * Attribute (catalogue)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatAttrVw extends TableImpl<CatAttrVwRecord> {

    private static final long serialVersionUID = 34425741;

    /**
     * The reference instance of <code>CAT.CAT_ATTR_VW</code>
     */
    public static final CatAttrVw CAT_ATTR_VW = new CatAttrVw();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CatAttrVwRecord> getRecordType() {
        return CatAttrVwRecord.class;
    }

    /**
     * The column <code>CAT.CAT_ATTR_VW.MANDATORY</code>. Marks mandatory attribute; only valid for columns (attribute type=C) and only affects way entity's PG package is generated.
     */
    public final TableField<CatAttrVwRecord, String> MANDATORY = createField("MANDATORY", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Marks mandatory attribute; only valid for columns (attribute type=C) and only affects way entity's PG package is generated.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ORDERED</code>. This column represents order (either globally or within children of one parent - see Ordering Group attribute).
     */
    public final TableField<CatAttrVwRecord, String> ORDERED = createField("ORDERED", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "This column represents order (either globally or within children of one parent - see Ordering Group attribute).");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ORDGROUP</code>. Parent attribute (or comma delimited list of parent attributes). Only used when ordered is set to Y - this column is then treated as ordering within group, made by same values of parent attributes
     */
    public final TableField<CatAttrVwRecord, String> ORDGROUP = createField("ORDGROUP", org.jooq.impl.SQLDataType.VARCHAR(200), this, "Parent attribute (or comma delimited list of parent attributes). Only used when ordered is set to Y - this column is then treated as ordering within group, made by same values of parent attributes");

    /**
     * The column <code>CAT.CAT_ATTR_VW.DEFVALUE</code>. Default value. Only used in generator, should not be changed on installations and is only valid for C (column) attributes.
     */
    public final TableField<CatAttrVwRecord, String> DEFVALUE = createField("DEFVALUE", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Default value. Only used in generator, should not be changed on installations and is only valid for C (column) attributes.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.MULTICREATE</code>. Create function accepts multiline in this attribute. Only valid for (C)olumn type attributes with domains UID and REF
     */
    public final TableField<CatAttrVwRecord, String> MULTICREATE = createField("MULTICREATE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Create function accepts multiline in this attribute. Only valid for (C)olumn type attributes with domains UID and REF");

    /**
     * The column <code>CAT.CAT_ATTR_VW.GENCOPY</code>. Generate mp_Copy_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public final TableField<CatAttrVwRecord, String> GENCOPY = createField("GENCOPY", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Generate mp_Copy_<***> procedure based on link, represented by this column, to PG package.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.GENMOVE</code>. Generate mp_Move_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public final TableField<CatAttrVwRecord, String> GENMOVE = createField("GENMOVE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Generate mp_Move_<***> procedure based on link, represented by this column, to PG package.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.GENDELETE</code>. Generate mp_Delete_&lt;***&gt; procedure based on link, represented by this column, to PG package.
     */
    public final TableField<CatAttrVwRecord, String> GENDELETE = createField("GENDELETE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Generate mp_Delete_<***> procedure based on link, represented by this column, to PG package.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.TEXTSRC_ID</code>. Source attribute for translated attribute (only for translated attributes)
     */
    public final TableField<CatAttrVwRecord, BigInteger> TEXTSRC_ID = createField("TEXTSRC_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Source attribute for translated attribute (only for translated attributes)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.HIERARCHICAL</code>.
     */
    public final TableField<CatAttrVwRecord, String> HIERARCHICAL = createField("HIERARCHICAL", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ISINTABLE</code>. Attribute is implemented in table of this Entity
     */
    public final TableField<CatAttrVwRecord, String> ISINTABLE = createField("ISINTABLE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Attribute is implemented in table of this Entity");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ISOWN</code>. Attribute is not inherited
     */
    public final TableField<CatAttrVwRecord, String> ISOWN = createField("ISOWN", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Attribute is not inherited");

    /**
     * The column <code>CAT.CAT_ATTR_VW.VALIDATED</code>. Specifies if validation is supported for given attribute. Is used by client to determine if editation in validate edit should be allowed when this attribute is used as format, or if seelction through LOV is required.
     */
    public final TableField<CatAttrVwRecord, String> VALIDATED = createField("VALIDATED", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Specifies if validation is supported for given attribute. Is used by client to determine if editation in validate edit should be allowed when this attribute is used as format, or if seelction through LOV is required.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ATTR_ID</code>.
     */
    public final TableField<CatAttrVwRecord, BigInteger> ATTR_ID = createField("ATTR_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false), this, "");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ENTITY_ID</code>. UID of entity attribute belongs to
     */
    public final TableField<CatAttrVwRecord, BigInteger> ENTITY_ID = createField("ENTITY_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false), this, "UID of entity attribute belongs to");

    /**
     * The column <code>CAT.CAT_ATTR_VW.NAME_NM</code>. Internal name of attribute (name of column / textcolumn in database); also default for shortname
     */
    public final TableField<CatAttrVwRecord, String> NAME_NM = createField("NAME_NM", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "Internal name of attribute (name of column / textcolumn in database); also default for shortname");

    /**
     * The column <code>CAT.CAT_ATTR_VW.NAME</code>. Name of attribute
     */
    public final TableField<CatAttrVwRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "Name of attribute");

    /**
     * The column <code>CAT.CAT_ATTR_VW.NOTE</code>. Note; initialized from comment on given column for "C" and "T" attributes
     */
    public final TableField<CatAttrVwRecord, String> NOTE = createField("NOTE", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Note; initialized from comment on given column for \"C\" and \"T\" attributes");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ATTRTYPE</code>. Type of attribute (C=column, T=text column, F=free attribute, I=financial attribute, Q=free SQL, O=formula)
     */
    public final TableField<CatAttrVwRecord, String> ATTRTYPE = createField("ATTRTYPE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Type of attribute (C=column, T=text column, F=free attribute, I=financial attribute, Q=free SQL, O=formula)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ISCUSTOM</code>. Custom for instalation
     */
    public final TableField<CatAttrVwRecord, String> ISCUSTOM = createField("ISCUSTOM", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Custom for instalation");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ISUSED</code>. Used on installation
     */
    public final TableField<CatAttrVwRecord, String> ISUSED = createField("ISUSED", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Used on installation");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ATTRGRP_ID</code>. Attribute group attribute belongs to; used for grouping free or financial attributes on client
     */
    public final TableField<CatAttrVwRecord, BigInteger> ATTRGRP_ID = createField("ATTRGRP_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Attribute group attribute belongs to; used for grouping free or financial attributes on client");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ORD</code>. Ordering of attributes within group; attributes with same ORD are usually ordered using name
Ordering is used for generate
     */
    public final TableField<CatAttrVwRecord, Integer> ORD = createField("ORD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Ordering of attributes within group; attributes with same ORD are usually ordered using name\nOrdering is used for generate");

    /**
     * The column <code>CAT.CAT_ATTR_VW.DOMAIN_ID</code>. Domain
     */
    public final TableField<CatAttrVwRecord, BigInteger> DOMAIN_ID = createField("DOMAIN_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false), this, "Domain");

    /**
     * The column <code>CAT.CAT_ATTR_VW.SUBDOMAIN_NM</code>. Subdomain - closer specification of domain
     */
    public final TableField<CatAttrVwRecord, String> SUBDOMAIN_NM = createField("SUBDOMAIN_NM", org.jooq.impl.SQLDataType.VARCHAR(200), this, "Subdomain - closer specification of domain");

    /**
     * The column <code>CAT.CAT_ATTR_VW.QVISIBLE</code>. Attribute is visible to users by default; setting can be overriden on profile level (see attribute profile settings).
     */
    public final TableField<CatAttrVwRecord, String> QVISIBLE = createField("QVISIBLE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Attribute is visible to users by default; setting can be overriden on profile level (see attribute profile settings).");

    /**
     * The column <code>CAT.CAT_ATTR_VW.LLENGTH</code>. Default length of atribute in lists
     */
    public final TableField<CatAttrVwRecord, Integer> LLENGTH = createField("LLENGTH", org.jooq.impl.SQLDataType.INTEGER, this, "Default length of atribute in lists");

    /**
     * The column <code>CAT.CAT_ATTR_VW.INDEXED</code>. Column is indexed; only usable for "C" attributes
     */
    public final TableField<CatAttrVwRecord, String> INDEXED = createField("INDEXED", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Column is indexed; only usable for \"C\" attributes");

    /**
     * The column <code>CAT.CAT_ATTR_VW.UPNAME_NM</code>. Name of upper-cased column; only usable for "C" or "T" attributes
     */
    public final TableField<CatAttrVwRecord, String> UPNAME_NM = createField("UPNAME_NM", org.jooq.impl.SQLDataType.VARCHAR(200), this, "Name of upper-cased column; only usable for \"C\" or \"T\" attributes");

    /**
     * The column <code>CAT.CAT_ATTR_VW.READONLY</code>. Value of attribute cannot be (directly) set by user.
- for columns and text (translated) attributes this has to be N, no checking is performed
- for formulas and SQL attributes, this has to be Y as it is never possible to modify their values
- for financial attributes, it is not possible to set value (or even define accounting rule for change of value) if attribute is read-only; value should be changed either through other financial attribute or by creating accounting records using other methods (through planned operations or some interface). If it is not read-only, accounting rule must be defined
- for free attributes, if free attribute is marked as read-only, user cannot change its value directly, it is only possible to change it using PG version of mp_Set with p_ChangeReadOnly=TRUE. It can be used for attributes which are replicated from other system or set through CP interface of some entity
     */
    public final TableField<CatAttrVwRecord, String> READONLY = createField("READONLY", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Value of attribute cannot be (directly) set by user.\n- for columns and text (translated) attributes this has to be N, no checking is performed\n- for formulas and SQL attributes, this has to be Y as it is never possible to modify their values\n- for financial attributes, it is not possible to set value (or even define accounting rule for change of value) if attribute is read-only; value should be changed either through other financial attribute or by creating accounting records using other methods (through planned operations or some interface). If it is not read-only, accounting rule must be defined\n- for free attributes, if free attribute is marked as read-only, user cannot change its value directly, it is only possible to change it using PG version of mp_Set with p_ChangeReadOnly=TRUE. It can be used for attributes which are replicated from other system or set through CP interface of some entity");

    /**
     * The column <code>CAT.CAT_ATTR_VW.GETOPTYPE_ID</code>. Operation type tested when accessing value of attribute
     */
    public final TableField<CatAttrVwRecord, BigInteger> GETOPTYPE_ID = createField("GETOPTYPE_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Operation type tested when accessing value of attribute");

    /**
     * The column <code>CAT.CAT_ATTR_VW.SETOPTYPE_ID</code>. Operation type tested when changing value of attribute
     */
    public final TableField<CatAttrVwRecord, BigInteger> SETOPTYPE_ID = createField("SETOPTYPE_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Operation type tested when changing value of attribute");

    /**
     * The column <code>CAT.CAT_ATTR_VW.RESETOPTYPE_ID</code>. Operation type tested when changing value of attribute to NULL; if not specified, SETOPTYPE_ID is used instead
     */
    public final TableField<CatAttrVwRecord, BigInteger> RESETOPTYPE_ID = createField("RESETOPTYPE_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Operation type tested when changing value of attribute to NULL; if not specified, SETOPTYPE_ID is used instead");

    /**
     * The column <code>CAT.CAT_ATTR_VW.CONFIRMOTHER</code>. Used for confirmation attributes; value of N means that user cannot set who confirmed action
     */
    public final TableField<CatAttrVwRecord, String> CONFIRMOTHER = createField("CONFIRMOTHER", org.jooq.impl.SQLDataType.CHAR(1), this, "Used for confirmation attributes; value of N means that user cannot set who confirmed action");

    /**
     * The column <code>CAT.CAT_ATTR_VW.SETOTHEROPTYPE_ID</code>. Operation type tested when changing value of CONFIRM attribute to person other than logged-in user; NULL means same rules apply as for SETOPTYPE_ID
     */
    public final TableField<CatAttrVwRecord, BigInteger> SETOTHEROPTYPE_ID = createField("SETOTHEROPTYPE_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Operation type tested when changing value of CONFIRM attribute to person other than logged-in user; NULL means same rules apply as for SETOPTYPE_ID");

    /**
     * The column <code>CAT.CAT_ATTR_VW.MULTIVALUE</code>. Multivalue allowed; valid only for free attributes
     */
    public final TableField<CatAttrVwRecord, String> MULTIVALUE = createField("MULTIVALUE", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Multivalue allowed; valid only for free attributes");

    /**
     * The column <code>CAT.CAT_ATTR_VW.LOGALLOWED</code>. Logging/dictionary indexing is supported
     */
    public final TableField<CatAttrVwRecord, String> LOGALLOWED = createField("LOGALLOWED", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Logging/dictionary indexing is supported");

    /**
     * The column <code>CAT.CAT_ATTR_VW.LOGLEVEL</code>. Log level (N=none, C=current value, H=changes log(history))
     */
    public final TableField<CatAttrVwRecord, String> LOGLEVEL = createField("LOGLEVEL", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Log level (N=none, C=current value, H=changes log(history))");

    /**
     * The column <code>CAT.CAT_ATTR_VW.DICTTYPE</code>. Type of storage of attribute in dictionary
     */
    public final TableField<CatAttrVwRecord, String> DICTTYPE = createField("DICTTYPE", org.jooq.impl.SQLDataType.CHAR(1), this, "Type of storage of attribute in dictionary");

    /**
     * The column <code>CAT.CAT_ATTR_VW.DICTDEL1</code>. Terms delimiter
     */
    public final TableField<CatAttrVwRecord, String> DICTDEL1 = createField("DICTDEL1", org.jooq.impl.SQLDataType.VARCHAR(10), this, "Terms delimiter");

    /**
     * The column <code>CAT.CAT_ATTR_VW.DICTDEL2</code>. Terms delimiter
     */
    public final TableField<CatAttrVwRecord, String> DICTDEL2 = createField("DICTDEL2", org.jooq.impl.SQLDataType.VARCHAR(10), this, "Terms delimiter");

    /**
     * The column <code>CAT.CAT_ATTR_VW.TBCODE_CD</code>. Code used to evaluate attribute value (when used internally); for "X" and "O" atributes
     */
    public final TableField<CatAttrVwRecord, String> TBCODE_CD = createField("TBCODE_CD", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Code used to evaluate attribute value (when used internally); for \"X\" and \"O\" atributes");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ACCOUNTRULE_NM</code>. Internal name of an accounting rule to be used to book the value for object (only for financial attributes)
     */
    public final TableField<CatAttrVwRecord, String> ACCOUNTRULE_NM = createField("ACCOUNTRULE_NM", org.jooq.impl.SQLDataType.VARCHAR(200), this, "Internal name of an accounting rule to be used to book the value for object (only for financial attributes)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.ACCDOCOBJECTFORMULA_ID</code>. Accounting document, created when changing value of this financial attribute will be connected to object, evaluated using this attribute. When left blank, document will be connected to object on which action was called (only for financial attributes)
     */
    public final TableField<CatAttrVwRecord, BigInteger> ACCDOCOBJECTFORMULA_ID = createField("ACCDOCOBJECTFORMULA_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Accounting document, created when changing value of this financial attribute will be connected to object, evaluated using this attribute. When left blank, document will be connected to object on which action was called (only for financial attributes)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.OWNERFORMULA_ID</code>. Owner of ledger used to evaluate value of financial attribute.
     */
    public final TableField<CatAttrVwRecord, BigInteger> OWNERFORMULA_ID = createField("OWNERFORMULA_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Owner of ledger used to evaluate value of financial attribute.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.FROMOBJECTFORMULA_ID</code>. Used when value of financial attribute is changed - value of this attribute is object to be used on spent side of accounting record
     */
    public final TableField<CatAttrVwRecord, BigInteger> FROMOBJECTFORMULA_ID = createField("FROMOBJECTFORMULA_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Used when value of financial attribute is changed - value of this attribute is object to be used on spent side of accounting record");

    /**
     * The column <code>CAT.CAT_ATTR_VW.TOOBJECTFORMULA_ID</code>. Used when value of financial attribute is changed - value of this attribute is object to be used on received side of accounting record
     */
    public final TableField<CatAttrVwRecord, BigInteger> TOOBJECTFORMULA_ID = createField("TOOBJECTFORMULA_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Used when value of financial attribute is changed - value of this attribute is object to be used on received side of accounting record");

    /**
     * The column <code>CAT.CAT_ATTR_VW.APPROXRECORD</code>. Indicates if the created accounting record will be approximate (only for financial attributes)
     */
    public final TableField<CatAttrVwRecord, String> APPROXRECORD = createField("APPROXRECORD", org.jooq.impl.SQLDataType.CHAR(1), this, "Indicates if the created accounting record will be approximate (only for financial attributes)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.VALUEACCOUNT_NM</code>. Short name of account to read actual value (only for financial attributes)
     */
    public final TableField<CatAttrVwRecord, String> VALUEACCOUNT_NM = createField("VALUEACCOUNT_NM", org.jooq.impl.SQLDataType.VARCHAR(200), this, "Short name of account to read actual value (only for financial attributes)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.VALUEAMOUNTTYPE</code>. R(eceived), S(pent), T(otal) amount of the balance to read actual value (only for financial attributes)
     */
    public final TableField<CatAttrVwRecord, String> VALUEAMOUNTTYPE = createField("VALUEAMOUNTTYPE", org.jooq.impl.SQLDataType.CHAR(1), this, "R(eceived), S(pent), T(otal) amount of the balance to read actual value (only for financial attributes)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.DEFOWNER</code>. Default owner points to unit that acts as owner of given object for purpose of accounting
     */
    public final TableField<CatAttrVwRecord, String> DEFOWNER = createField("DEFOWNER", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Default owner points to unit that acts as owner of given object for purpose of accounting");

    /**
     * The column <code>CAT.CAT_ATTR_VW.DOCUMENTATION</code>. Addional documentation related to the attribute (not generated to the table column comment)
     */
    public final TableField<CatAttrVwRecord, String> DOCUMENTATION = createField("DOCUMENTATION", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Addional documentation related to the attribute (not generated to the table column comment)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.BITMAPORD</code>. Order in Attribute Set Bitmap, 0=Least Significant bit. Used internally in generated parts of PG packages (only for column attributes)
     */
    public final TableField<CatAttrVwRecord, Integer> BITMAPORD = createField("BITMAPORD", org.jooq.impl.SQLDataType.INTEGER, this, "Order in Attribute Set Bitmap, 0=Least Significant bit. Used internally in generated parts of PG packages (only for column attributes)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.X_ISFLAGDEPBIND</code>.
     */
    public final TableField<CatAttrVwRecord, String> X_ISFLAGDEPBIND = createField("X_ISFLAGDEPBIND", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * The column <code>CAT.CAT_ATTR_VW.X_ISFLAGDEFATTR</code>. Shows if Attribute is used in any Flag Definition (via. FlagDefAttr, or DstAttr of any FlagDep)
     */
    public final TableField<CatAttrVwRecord, String> X_ISFLAGDEFATTR = createField("X_ISFLAGDEFATTR", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Shows if Attribute is used in any Flag Definition (via. FlagDefAttr, or DstAttr of any FlagDep)");

    /**
     * The column <code>CAT.CAT_ATTR_VW.COPIED</code>. Attribute value is copied in copy operations.
     */
    public final TableField<CatAttrVwRecord, String> COPIED = createField("COPIED", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "Attribute value is copied in copy operations.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.KEYORD</code>. Order of given attribute in key of given entity
     */
    public final TableField<CatAttrVwRecord, Integer> KEYORD = createField("KEYORD", org.jooq.impl.SQLDataType.INTEGER, this, "Order of given attribute in key of given entity");

    /**
     * The column <code>CAT.CAT_ATTR_VW.OPTYPETYPE_RF</code>. Specifies type of operation for UID / operation type attributes that support automatic optype creation
     */
    public final TableField<CatAttrVwRecord, BigInteger> OPTYPETYPE_RF = createField("OPTYPETYPE_RF", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Specifies type of operation for UID / operation type attributes that support automatic optype creation");

    /**
     * The column <code>CAT.CAT_ATTR_VW.IMGSRC_ID</code>. Reference to the image souce, which we should resize
     */
    public final TableField<CatAttrVwRecord, BigInteger> IMGSRC_ID = createField("IMGSRC_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Reference to the image souce, which we should resize");

    /**
     * The column <code>CAT.CAT_ATTR_VW.IMGWIDTH</code>. The width of the picture to resize
     */
    public final TableField<CatAttrVwRecord, Integer> IMGWIDTH = createField("IMGWIDTH", org.jooq.impl.SQLDataType.INTEGER, this, "The width of the picture to resize");

    /**
     * The column <code>CAT.CAT_ATTR_VW.IMGHEIGHT</code>. The height of the picture to resize
     */
    public final TableField<CatAttrVwRecord, Integer> IMGHEIGHT = createField("IMGHEIGHT", org.jooq.impl.SQLDataType.INTEGER, this, "The height of the picture to resize");

    /**
     * The column <code>CAT.CAT_ATTR_VW.FILESERVER_ID</code>. [KO150414-21B7CDA] Ukladani souboru mimo databazi
     */
    public final TableField<CatAttrVwRecord, BigInteger> FILESERVER_ID = createField("FILESERVER_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "[KO150414-21B7CDA] Ukladani souboru mimo databazi");

    /**
     * The column <code>CAT.CAT_ATTR_VW.GENMIGR</code>. Used for generator of migration framework
     */
    public final TableField<CatAttrVwRecord, String> GENMIGR = createField("GENMIGR", org.jooq.impl.SQLDataType.CHAR(1), this, "Used for generator of migration framework");

    /**
     * The column <code>CAT.CAT_ATTR_VW.EVALCVALUE</code>. Evaluate and store text from binary document. Text representation can be used in fulltext searches - thus, it should be enabled for properties, that are included in fulltext search flagdef. Is always empty for domains other than BLOB
     */
    public final TableField<CatAttrVwRecord, String> EVALCVALUE = createField("EVALCVALUE", org.jooq.impl.SQLDataType.CHAR(1), this, "Evaluate and store text from binary document. Text representation can be used in fulltext searches - thus, it should be enabled for properties, that are included in fulltext search flagdef. Is always empty for domains other than BLOB");

    /**
     * The column <code>CAT.CAT_ATTR_VW.OPTLOBLIMIT</code>. Optional limit for length of lob free atribut. It show alert.  The limit  is in bytes
     */
    public final TableField<CatAttrVwRecord, BigDecimal> OPTLOBLIMIT = createField("OPTLOBLIMIT", org.jooq.impl.SQLDataType.NUMERIC, this, "Optional limit for length of lob free atribut. It show alert.  The limit  is in bytes");

    /**
     * The column <code>CAT.CAT_ATTR_VW.MANLOBLIMIT</code>. Mandatory limit for length of lob free atribute. It show error. The limit is in bytes.
     */
    public final TableField<CatAttrVwRecord, BigDecimal> MANLOBLIMIT = createField("MANLOBLIMIT", org.jooq.impl.SQLDataType.NUMERIC, this, "Mandatory limit for length of lob free atribute. It show error. The limit is in bytes.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_ISACTIVE</code>. Whether attribute or any of its ancestors has Is Own flag set
     */
    public final TableField<CatAttrVwRecord, String> C_ISACTIVE = createField("C_ISACTIVE", org.jooq.impl.SQLDataType.VARCHAR(1), this, "Whether attribute or any of its ancestors has Is Own flag set");

    /**
     * The column <code>CAT.CAT_ATTR_VW.NLSSHORT</code>. Shortname
     */
    public final TableField<CatAttrVwRecord, String> NLSSHORT = createField("NLSSHORT", org.jooq.impl.SQLDataType.NVARCHAR(200), this, "Shortname");

    /**
     * The column <code>CAT.CAT_ATTR_VW.NLSNAME</code>. Name
     */
    public final TableField<CatAttrVwRecord, String> NLSNAME = createField("NLSNAME", org.jooq.impl.SQLDataType.NVARCHAR(200), this, "Name");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_ANCESTOR_ID</code>. Ancestor is attribute in entity ancestor with same internal name.
     */
    public final TableField<CatAttrVwRecord, BigDecimal> C_ANCESTOR_ID = createField("C_ANCESTOR_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "Ancestor is attribute in entity ancestor with same internal name.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_DOCUMENTATION</code>. Documentation, potentially inherited from attribute's ancestor
     */
    public final TableField<CatAttrVwRecord, String> C_DOCUMENTATION = createField("C_DOCUMENTATION", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Documentation, potentially inherited from attribute's ancestor");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_ENTITY_NM</code>.
     */
    public final TableField<CatAttrVwRecord, String> C_ENTITY_NM = createField("C_ENTITY_NM", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_GETOPTYPEAUTO</code>.
     */
    public final TableField<CatAttrVwRecord, String> C_GETOPTYPEAUTO = createField("C_GETOPTYPEAUTO", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_NOTE</code>. Note, potentially inherited from attribute's ancestor
     */
    public final TableField<CatAttrVwRecord, String> C_NOTE = createField("C_NOTE", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Note, potentially inherited from attribute's ancestor");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_OWNERFORMULA_ID</code>. Effective value of attribute, used to evaluate owner of object (and thus ledger) to be used with given financial attribute.
     */
    public final TableField<CatAttrVwRecord, BigDecimal> C_OWNERFORMULA_ID = createField("C_OWNERFORMULA_ID", org.jooq.impl.SQLDataType.NUMERIC, this, "Effective value of attribute, used to evaluate owner of object (and thus ledger) to be used with given financial attribute.");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_RESETOPTYPEAUTO</code>.
     */
    public final TableField<CatAttrVwRecord, String> C_RESETOPTYPEAUTO = createField("C_RESETOPTYPEAUTO", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_SETOPTYPEAUTO</code>.
     */
    public final TableField<CatAttrVwRecord, String> C_SETOPTYPEAUTO = createField("C_SETOPTYPEAUTO", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>CAT.CAT_ATTR_VW.C_SETOTHEROPTYPEAUTO</code>.
     */
    public final TableField<CatAttrVwRecord, String> C_SETOTHEROPTYPEAUTO = createField("C_SETOTHEROPTYPEAUTO", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>CAT.CAT_ATTR_VW.I_DOCUMENTATION</code>. Description in attribute's ancestor
     */
    public final TableField<CatAttrVwRecord, String> I_DOCUMENTATION = createField("I_DOCUMENTATION", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Description in attribute's ancestor");

    /**
     * The column <code>CAT.CAT_ATTR_VW.I_NOTE</code>. Note in attribute's ancestor
     */
    public final TableField<CatAttrVwRecord, String> I_NOTE = createField("I_NOTE", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Note in attribute's ancestor");

    /**
     * The column <code>CAT.CAT_ATTR_VW.NLSNOTE</code>. Note
     */
    public final TableField<CatAttrVwRecord, String> NLSNOTE = createField("NLSNOTE", org.jooq.impl.SQLDataType.NVARCHAR(2000), this, "Note");

    /**
     * Create a <code>CAT.CAT_ATTR_VW</code> table reference
     */
    public CatAttrVw() {
        this(DSL.name("CAT_ATTR_VW"), null);
    }

    /**
     * Create an aliased <code>CAT.CAT_ATTR_VW</code> table reference
     */
    public CatAttrVw(String alias) {
        this(DSL.name(alias), CAT_ATTR_VW);
    }

    /**
     * Create an aliased <code>CAT.CAT_ATTR_VW</code> table reference
     */
    public CatAttrVw(Name alias) {
        this(alias, CAT_ATTR_VW);
    }

    private CatAttrVw(Name alias, Table<CatAttrVwRecord> aliased) {
        this(alias, aliased, null);
    }

    private CatAttrVw(Name alias, Table<CatAttrVwRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Generated view for entity ATTR\nAttribute (catalogue)"));
    }

    public <O extends Record> CatAttrVw(Table<O> child, ForeignKey<O, CatAttrVwRecord> key) {
        super(child, key, CAT_ATTR_VW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cat.CAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatAttrVw as(String alias) {
        return new CatAttrVw(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatAttrVw as(Name alias) {
        return new CatAttrVw(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CatAttrVw rename(String name) {
        return new CatAttrVw(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CatAttrVw rename(Name name) {
        return new CatAttrVw(name, null);
    }
}
