/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.catalogue.db.tables;


import com.provys.ealoader.catalogue.db.Cat;
import com.provys.ealoader.catalogue.db.tables.records.CatEntitygrpVwRecord;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Generated view for entity ENTITYGRP
 * Entity group
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatEntitygrpVw extends TableImpl<CatEntitygrpVwRecord> {

    private static final long serialVersionUID = -677378329;

    /**
     * The reference instance of <code>CAT.CAT_ENTITYGRP_VW</code>
     */
    public static final CatEntitygrpVw CAT_ENTITYGRP_VW = new CatEntitygrpVw();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CatEntitygrpVwRecord> getRecordType() {
        return CatEntitygrpVwRecord.class;
    }

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.ENTITYGRP_ID</code>. UID
     */
    public final TableField<CatEntitygrpVwRecord, BigInteger> ENTITYGRP_ID = createField("ENTITYGRP_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false), this, "UID");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.PARENT_ID</code>. Parent group
     */
    public final TableField<CatEntitygrpVwRecord, BigInteger> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "Parent group");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.NAME_NM</code>. Internal name
     */
    public final TableField<CatEntitygrpVwRecord, String> NAME_NM = createField("NAME_NM", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "Internal name");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.NAME</code>. Name of group; translated as NLSNAME
     */
    public final TableField<CatEntitygrpVwRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "Name of group; translated as NLSNAME");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.X_UPNAME</code>. Calculated column - uppercase of NAME
     */
    public final TableField<CatEntitygrpVwRecord, String> X_UPNAME = createField("X_UPNAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "Calculated column - uppercase of NAME");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.NOTE</code>. Short description; translated as NLSNOTE
     */
    public final TableField<CatEntitygrpVwRecord, String> NOTE = createField("NOTE", org.jooq.impl.SQLDataType.VARCHAR(2000), this, "Short description; translated as NLSNOTE");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.ORD</code>. Ordering of entity groups within their parent / absolute; items with same ORD are sorted using name
     */
    public final TableField<CatEntitygrpVwRecord, Integer> ORD = createField("ORD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "Ordering of entity groups within their parent / absolute; items with same ORD are sorted using name");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.NLSNAME</code>.
     */
    public final TableField<CatEntitygrpVwRecord, String> NLSNAME = createField("NLSNAME", org.jooq.impl.SQLDataType.NVARCHAR(200), this, "");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.C_FULLNAME</code>. Full name (e.g. including hierarchy of parent groups)
     */
    public final TableField<CatEntitygrpVwRecord, String> C_FULLNAME = createField("C_FULLNAME", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Full name (e.g. including hierarchy of parent groups)");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.C_FULLNLSNAME</code>. Full translated name (e.g. including hierarchy of parent groups)
     */
    public final TableField<CatEntitygrpVwRecord, String> C_FULLNLSNAME = createField("C_FULLNLSNAME", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Full translated name (e.g. including hierarchy of parent groups)");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.C_FULLNM</code>. Full internal name (e.g. including hierarchy of parent groups)
     */
    public final TableField<CatEntitygrpVwRecord, String> C_FULLNM = createField("C_FULLNM", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "Full internal name (e.g. including hierarchy of parent groups)");

    /**
     * The column <code>CAT.CAT_ENTITYGRP_VW.NLSNOTE</code>.
     */
    public final TableField<CatEntitygrpVwRecord, String> NLSNOTE = createField("NLSNOTE", org.jooq.impl.SQLDataType.NVARCHAR(2000), this, "");

    /**
     * Create a <code>CAT.CAT_ENTITYGRP_VW</code> table reference
     */
    public CatEntitygrpVw() {
        this(DSL.name("CAT_ENTITYGRP_VW"), null);
    }

    /**
     * Create an aliased <code>CAT.CAT_ENTITYGRP_VW</code> table reference
     */
    public CatEntitygrpVw(String alias) {
        this(DSL.name(alias), CAT_ENTITYGRP_VW);
    }

    /**
     * Create an aliased <code>CAT.CAT_ENTITYGRP_VW</code> table reference
     */
    public CatEntitygrpVw(Name alias) {
        this(alias, CAT_ENTITYGRP_VW);
    }

    private CatEntitygrpVw(Name alias, Table<CatEntitygrpVwRecord> aliased) {
        this(alias, aliased, null);
    }

    private CatEntitygrpVw(Name alias, Table<CatEntitygrpVwRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Generated view for entity ENTITYGRP\nEntity group"));
    }

    public <O extends Record> CatEntitygrpVw(Table<O> child, ForeignKey<O, CatEntitygrpVwRecord> key) {
        super(child, key, CAT_ENTITYGRP_VW);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cat.CAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatEntitygrpVw as(String alias) {
        return new CatEntitygrpVw(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CatEntitygrpVw as(Name alias) {
        return new CatEntitygrpVw(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CatEntitygrpVw rename(String name) {
        return new CatEntitygrpVw(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CatEntitygrpVw rename(Name name) {
        return new CatEntitygrpVw(name, null);
    }
}
