/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.ea.db;


import com.provys.ealoader.ea.db.tables.TAttribute;
import com.provys.ealoader.ea.db.tables.TObject;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>KER</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_ATTRIBUTE_CLASSIFIER = Indexes0.IX_ATTRIBUTE_CLASSIFIER;
    public static final Index IX_ATTRIBUTE_NAME = Indexes0.IX_ATTRIBUTE_NAME;
    public static final Index IX_ATTRIBUTE_OBJECTID = Indexes0.IX_ATTRIBUTE_OBJECTID;
    public static final Index IX_ATTRIBUTE_TYPE = Indexes0.IX_ATTRIBUTE_TYPE;
    public static final Index PK_ATTRIBUTE = Indexes0.PK_ATTRIBUTE;
    public static final Index UQ_ATTRIBUTE_EAGUID = Indexes0.UQ_ATTRIBUTE_EAGUID;
    public static final Index IX_OBJECT_CLASSIFIER = Indexes0.IX_OBJECT_CLASSIFIER;
    public static final Index IX_OBJECT_CLASSIFIERGUID = Indexes0.IX_OBJECT_CLASSIFIERGUID;
    public static final Index IX_OBJECT_EAGUIDCLASSIFIER = Indexes0.IX_OBJECT_EAGUIDCLASSIFIER;
    public static final Index IX_OBJECT_EVENTFLAGS = Indexes0.IX_OBJECT_EVENTFLAGS;
    public static final Index IX_OBJECT_NAME = Indexes0.IX_OBJECT_NAME;
    public static final Index IX_OBJECT_NTYPE = Indexes0.IX_OBJECT_NTYPE;
    public static final Index IX_OBJECT_OBJECTTYPE = Indexes0.IX_OBJECT_OBJECTTYPE;
    public static final Index IX_OBJECT_PACKAGEID = Indexes0.IX_OBJECT_PACKAGEID;
    public static final Index IX_OBJECT_PARENTID = Indexes0.IX_OBJECT_PARENTID;
    public static final Index IX_OBJECT_PDATA1 = Indexes0.IX_OBJECT_PDATA1;
    public static final Index IX_OBJECT_PDATA5 = Indexes0.IX_OBJECT_PDATA5;
    public static final Index IX_OBJECT_PKGIDPDATA1CLASS = Indexes0.IX_OBJECT_PKGIDPDATA1CLASS;
    public static final Index PK_OBJECT = Indexes0.PK_OBJECT;
    public static final Index UQ_OBJ_EAGUID = Indexes0.UQ_OBJ_EAGUID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index IX_ATTRIBUTE_CLASSIFIER = Internal.createIndex("IX_ATTRIBUTE_CLASSIFIER", TAttribute.T_ATTRIBUTE, new OrderField[] { TAttribute.T_ATTRIBUTE.CLASSIFIER }, false);
        public static Index IX_ATTRIBUTE_NAME = Internal.createIndex("IX_ATTRIBUTE_NAME", TAttribute.T_ATTRIBUTE, new OrderField[] { TAttribute.T_ATTRIBUTE.NAME }, false);
        public static Index IX_ATTRIBUTE_OBJECTID = Internal.createIndex("IX_ATTRIBUTE_OBJECTID", TAttribute.T_ATTRIBUTE, new OrderField[] { TAttribute.T_ATTRIBUTE.OBJECT_ID }, false);
        public static Index IX_ATTRIBUTE_TYPE = Internal.createIndex("IX_ATTRIBUTE_TYPE", TAttribute.T_ATTRIBUTE, new OrderField[] { TAttribute.T_ATTRIBUTE.TYPE }, false);
        public static Index PK_ATTRIBUTE = Internal.createIndex("PK_ATTRIBUTE", TAttribute.T_ATTRIBUTE, new OrderField[] { TAttribute.T_ATTRIBUTE.ID }, true);
        public static Index UQ_ATTRIBUTE_EAGUID = Internal.createIndex("UQ_ATTRIBUTE_EAGUID", TAttribute.T_ATTRIBUTE, new OrderField[] { TAttribute.T_ATTRIBUTE.EA_GUID }, true);
        public static Index IX_OBJECT_CLASSIFIER = Internal.createIndex("IX_OBJECT_CLASSIFIER", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.CLASSIFIER }, false);
        public static Index IX_OBJECT_CLASSIFIERGUID = Internal.createIndex("IX_OBJECT_CLASSIFIERGUID", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.CLASSIFIER_GUID }, false);
        public static Index IX_OBJECT_EAGUIDCLASSIFIER = Internal.createIndex("IX_OBJECT_EAGUIDCLASSIFIER", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.EA_GUID, TObject.T_OBJECT.CLASSIFIER }, false);
        public static Index IX_OBJECT_EVENTFLAGS = Internal.createIndex("IX_OBJECT_EVENTFLAGS", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.EVENTFLAGS }, false);
        public static Index IX_OBJECT_NAME = Internal.createIndex("IX_OBJECT_NAME", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.NAME }, false);
        public static Index IX_OBJECT_NTYPE = Internal.createIndex("IX_OBJECT_NTYPE", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.NTYPE }, false);
        public static Index IX_OBJECT_OBJECTTYPE = Internal.createIndex("IX_OBJECT_OBJECTTYPE", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.OBJECT_TYPE }, false);
        public static Index IX_OBJECT_PACKAGEID = Internal.createIndex("IX_OBJECT_PACKAGEID", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.PACKAGE_ID }, false);
        public static Index IX_OBJECT_PARENTID = Internal.createIndex("IX_OBJECT_PARENTID", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.PARENTID }, false);
        public static Index IX_OBJECT_PDATA1 = Internal.createIndex("IX_OBJECT_PDATA1", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.PDATA1 }, false);
        public static Index IX_OBJECT_PDATA5 = Internal.createIndex("IX_OBJECT_PDATA5", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.PDATA5 }, false);
        public static Index IX_OBJECT_PKGIDPDATA1CLASS = Internal.createIndex("IX_OBJECT_PKGIDPDATA1CLASS", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.PACKAGE_ID, TObject.T_OBJECT.PDATA1, TObject.T_OBJECT.CLASSIFIER }, false);
        public static Index PK_OBJECT = Internal.createIndex("PK_OBJECT", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.OBJECT_ID }, true);
        public static Index UQ_OBJ_EAGUID = Internal.createIndex("UQ_OBJ_EAGUID", TObject.T_OBJECT, new OrderField[] { TObject.T_OBJECT.EA_GUID }, true);
    }
}
