/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.ea.db;


import com.provys.ealoader.ea.db.tables.TAttribute;
import com.provys.ealoader.ea.db.tables.TObject;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ker extends SchemaImpl {

    private static final long serialVersionUID = 619615616;

    /**
     * The reference instance of <code>KER</code>
     */
    public static final Ker KER = new Ker();

    /**
     * The table <code>KER.T_ATTRIBUTE</code>.
     */
    public final TAttribute T_ATTRIBUTE = com.provys.ealoader.ea.db.tables.TAttribute.T_ATTRIBUTE;

    /**
     * The table <code>KER.T_OBJECT</code>.
     */
    public final TObject T_OBJECT = com.provys.ealoader.ea.db.tables.TObject.T_OBJECT;

    /**
     * No further instances allowed
     */
    private Ker() {
        super("KER", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TAttribute.T_ATTRIBUTE,
            TObject.T_OBJECT);
    }
}
