/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.ea.db;


import com.provys.ealoader.ea.db.tables.TAttribute;
import com.provys.ealoader.ea.db.tables.TObject;
import com.provys.ealoader.ea.db.tables.records.TAttributeRecord;
import com.provys.ealoader.ea.db.tables.records.TObjectRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>KER</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TAttributeRecord> PK_ATTRIBUTE = UniqueKeys0.PK_ATTRIBUTE;
    public static final UniqueKey<TAttributeRecord> UQ_ATTRIBUTE_EAGUID = UniqueKeys0.UQ_ATTRIBUTE_EAGUID;
    public static final UniqueKey<TObjectRecord> PK_OBJECT = UniqueKeys0.PK_OBJECT;
    public static final UniqueKey<TObjectRecord> UQ_OBJ_EAGUID = UniqueKeys0.UQ_OBJ_EAGUID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TAttributeRecord> PK_ATTRIBUTE = Internal.createUniqueKey(TAttribute.T_ATTRIBUTE, "PK_ATTRIBUTE", TAttribute.T_ATTRIBUTE.ID);
        public static final UniqueKey<TAttributeRecord> UQ_ATTRIBUTE_EAGUID = Internal.createUniqueKey(TAttribute.T_ATTRIBUTE, "UQ_ATTRIBUTE_EAGUID", TAttribute.T_ATTRIBUTE.EA_GUID);
        public static final UniqueKey<TObjectRecord> PK_OBJECT = Internal.createUniqueKey(TObject.T_OBJECT, "PK_OBJECT", TObject.T_OBJECT.OBJECT_ID);
        public static final UniqueKey<TObjectRecord> UQ_OBJ_EAGUID = Internal.createUniqueKey(TObject.T_OBJECT, "UQ_OBJ_EAGUID", TObject.T_OBJECT.EA_GUID);
    }
}
