/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.ea.db;


import com.provys.ealoader.ea.db.tables.TAttribute;
import com.provys.ealoader.ea.db.tables.TObject;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in KER
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>KER.T_ATTRIBUTE</code>.
     */
    public static final TAttribute T_ATTRIBUTE = com.provys.ealoader.ea.db.tables.TAttribute.T_ATTRIBUTE;

    /**
     * The table <code>KER.T_OBJECT</code>.
     */
    public static final TObject T_OBJECT = com.provys.ealoader.ea.db.tables.TObject.T_OBJECT;
}
