/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.ea.db.tables.records;


import com.provys.ealoader.ea.db.tables.TAttribute;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAttributeRecord extends UpdatableRecordImpl<TAttributeRecord> {

    private static final long serialVersionUID = -1771619992;

    /**
     * Setter for <code>KER.T_ATTRIBUTE.OBJECT_ID</code>.
     */
    public void setObjectId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.OBJECT_ID</code>.
     */
    public Long getObjectId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.SCOPE</code>.
     */
    public void setScope(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.SCOPE</code>.
     */
    public String getScope() {
        return (String) get(2);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.STEREOTYPE</code>.
     */
    public void setStereotype(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.STEREOTYPE</code>.
     */
    public String getStereotype() {
        return (String) get(3);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.CONTAINMENT</code>.
     */
    public void setContainment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.CONTAINMENT</code>.
     */
    public String getContainment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.ISSTATIC</code>.
     */
    public void setIsstatic(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.ISSTATIC</code>.
     */
    public Long getIsstatic() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.ISCOLLECTION</code>.
     */
    public void setIscollection(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.ISCOLLECTION</code>.
     */
    public Long getIscollection() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.ISORDERED</code>.
     */
    public void setIsordered(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.ISORDERED</code>.
     */
    public Long getIsordered() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.ALLOWDUPLICATES</code>.
     */
    public void setAllowduplicates(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.ALLOWDUPLICATES</code>.
     */
    public Long getAllowduplicates() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.LOWERBOUND</code>.
     */
    public void setLowerbound(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.LOWERBOUND</code>.
     */
    public String getLowerbound() {
        return (String) get(9);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.UPPERBOUND</code>.
     */
    public void setUpperbound(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.UPPERBOUND</code>.
     */
    public String getUpperbound() {
        return (String) get(10);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.CONTAINER</code>.
     */
    public void setContainer(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.CONTAINER</code>.
     */
    public String getContainer() {
        return (String) get(11);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.NOTES</code>.
     */
    public void setNotes(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.NOTES</code>.
     */
    public String getNotes() {
        return (String) get(12);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.DERIVED</code>.
     */
    public void setDerived(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.DERIVED</code>.
     */
    public String getDerived() {
        return (String) get(13);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.ID</code>.
     */
    public void setId(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.ID</code>.
     */
    public Long getId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.POS</code>.
     */
    public void setPos(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.POS</code>.
     */
    public Long getPos() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.GENOPTION</code>.
     */
    public void setGenoption(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.GENOPTION</code>.
     */
    public String getGenoption() {
        return (String) get(16);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.LENGTH</code>.
     */
    public void setLength(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.LENGTH</code>.
     */
    public Long getLength() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.PRECISION</code>.
     */
    public void setPrecision(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.PRECISION</code>.
     */
    public Long getPrecision() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.SCALE</code>.
     */
    public void setScale(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.SCALE</code>.
     */
    public Long getScale() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.CONST</code>.
     */
    public void setConst(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.CONST</code>.
     */
    public Long getConst() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.STYLE</code>.
     */
    public void setStyle(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.STYLE</code>.
     */
    public String getStyle() {
        return (String) get(21);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.CLASSIFIER</code>.
     */
    public void setClassifier(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.CLASSIFIER</code>.
     */
    public String getClassifier() {
        return (String) get(22);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.Default</code>.
     */
    public void setDefault(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.Default</code>.
     */
    public String getDefault() {
        return (String) get(23);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.TYPE</code>.
     */
    public void setType(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.TYPE</code>.
     */
    public String getType() {
        return (String) get(24);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.EA_GUID</code>.
     */
    public void setEaGuid(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.EA_GUID</code>.
     */
    public String getEaGuid() {
        return (String) get(25);
    }

    /**
     * Setter for <code>KER.T_ATTRIBUTE.STYLEEX</code>.
     */
    public void setStyleex(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>KER.T_ATTRIBUTE.STYLEEX</code>.
     */
    public String getStyleex() {
        return (String) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAttributeRecord
     */
    public TAttributeRecord() {
        super(TAttribute.T_ATTRIBUTE);
    }

    /**
     * Create a detached, initialised TAttributeRecord
     */
    public TAttributeRecord(Long objectId, String name, String scope, String stereotype, String containment, Long isstatic, Long iscollection, Long isordered, Long allowduplicates, String lowerbound, String upperbound, String container, String notes, String derived, Long id, Long pos, String genoption, Long length, Long precision, Long scale, Long const_, String style, String classifier, String default_, String type, String eaGuid, String styleex) {
        super(TAttribute.T_ATTRIBUTE);

        set(0, objectId);
        set(1, name);
        set(2, scope);
        set(3, stereotype);
        set(4, containment);
        set(5, isstatic);
        set(6, iscollection);
        set(7, isordered);
        set(8, allowduplicates);
        set(9, lowerbound);
        set(10, upperbound);
        set(11, container);
        set(12, notes);
        set(13, derived);
        set(14, id);
        set(15, pos);
        set(16, genoption);
        set(17, length);
        set(18, precision);
        set(19, scale);
        set(20, const_);
        set(21, style);
        set(22, classifier);
        set(23, default_);
        set(24, type);
        set(25, eaGuid);
        set(26, styleex);
    }
}
