/*
 * This file is generated by jOOQ.
 */
package com.provys.ealoader.ea.db.tables.records;


import com.provys.ealoader.ea.db.tables.TObject;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TObjectRecord extends UpdatableRecordImpl<TObjectRecord> {

    private static final long serialVersionUID = -1766748961;

    /**
     * Setter for <code>KER.T_OBJECT.OBJECT_ID</code>.
     */
    public void setObjectId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.OBJECT_ID</code>.
     */
    public Long getObjectId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>KER.T_OBJECT.OBJECT_TYPE</code>.
     */
    public void setObjectType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.OBJECT_TYPE</code>.
     */
    public String getObjectType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>KER.T_OBJECT.DIAGRAM_ID</code>.
     */
    public void setDiagramId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.DIAGRAM_ID</code>.
     */
    public Long getDiagramId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>KER.T_OBJECT.NAME</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.NAME</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>KER.T_OBJECT.ALIAS</code>.
     */
    public void setAlias(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.ALIAS</code>.
     */
    public String getAlias() {
        return (String) get(4);
    }

    /**
     * Setter for <code>KER.T_OBJECT.AUTHOR</code>.
     */
    public void setAuthor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.AUTHOR</code>.
     */
    public String getAuthor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>KER.T_OBJECT.VERSION</code>.
     */
    public void setVersion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.VERSION</code>.
     */
    public String getVersion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>KER.T_OBJECT.NOTE</code>.
     */
    public void setNote(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.NOTE</code>.
     */
    public String getNote() {
        return (String) get(7);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PACKAGE_ID</code>.
     */
    public void setPackageId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PACKAGE_ID</code>.
     */
    public Long getPackageId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>KER.T_OBJECT.STEREOTYPE</code>.
     */
    public void setStereotype(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.STEREOTYPE</code>.
     */
    public String getStereotype() {
        return (String) get(9);
    }

    /**
     * Setter for <code>KER.T_OBJECT.NTYPE</code>.
     */
    public void setNtype(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.NTYPE</code>.
     */
    public Long getNtype() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>KER.T_OBJECT.COMPLEXITY</code>.
     */
    public void setComplexity(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.COMPLEXITY</code>.
     */
    public String getComplexity() {
        return (String) get(11);
    }

    /**
     * Setter for <code>KER.T_OBJECT.EFFORT</code>.
     */
    public void setEffort(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.EFFORT</code>.
     */
    public Long getEffort() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>KER.T_OBJECT.STYLE</code>.
     */
    public void setStyle(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.STYLE</code>.
     */
    public String getStyle() {
        return (String) get(13);
    }

    /**
     * Setter for <code>KER.T_OBJECT.BACKCOLOR</code>.
     */
    public void setBackcolor(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.BACKCOLOR</code>.
     */
    public Long getBackcolor() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>KER.T_OBJECT.BORDERSTYLE</code>.
     */
    public void setBorderstyle(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.BORDERSTYLE</code>.
     */
    public Long getBorderstyle() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>KER.T_OBJECT.BORDERWIDTH</code>.
     */
    public void setBorderwidth(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.BORDERWIDTH</code>.
     */
    public Long getBorderwidth() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>KER.T_OBJECT.FONTCOLOR</code>.
     */
    public void setFontcolor(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.FONTCOLOR</code>.
     */
    public Long getFontcolor() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>KER.T_OBJECT.BORDERCOLOR</code>.
     */
    public void setBordercolor(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.BORDERCOLOR</code>.
     */
    public Long getBordercolor() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>KER.T_OBJECT.CREATEDDATE</code>.
     */
    public void setCreateddate(Date value) {
        set(19, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.CREATEDDATE</code>.
     */
    public Date getCreateddate() {
        return (Date) get(19);
    }

    /**
     * Setter for <code>KER.T_OBJECT.MODIFIEDDATE</code>.
     */
    public void setModifieddate(Date value) {
        set(20, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.MODIFIEDDATE</code>.
     */
    public Date getModifieddate() {
        return (Date) get(20);
    }

    /**
     * Setter for <code>KER.T_OBJECT.STATUS</code>.
     */
    public void setStatus(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(21);
    }

    /**
     * Setter for <code>KER.T_OBJECT.ABSTRACT</code>.
     */
    public void setAbstract(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.ABSTRACT</code>.
     */
    public String getAbstract() {
        return (String) get(22);
    }

    /**
     * Setter for <code>KER.T_OBJECT.TAGGED</code>.
     */
    public void setTagged(Long value) {
        set(23, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.TAGGED</code>.
     */
    public Long getTagged() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PDATA1</code>.
     */
    public void setPdata1(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PDATA1</code>.
     */
    public String getPdata1() {
        return (String) get(24);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PDATA2</code>.
     */
    public void setPdata2(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PDATA2</code>.
     */
    public String getPdata2() {
        return (String) get(25);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PDATA3</code>.
     */
    public void setPdata3(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PDATA3</code>.
     */
    public String getPdata3() {
        return (String) get(26);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PDATA4</code>.
     */
    public void setPdata4(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PDATA4</code>.
     */
    public String getPdata4() {
        return (String) get(27);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PDATA5</code>.
     */
    public void setPdata5(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PDATA5</code>.
     */
    public String getPdata5() {
        return (String) get(28);
    }

    /**
     * Setter for <code>KER.T_OBJECT.CONCURRENCY</code>.
     */
    public void setConcurrency(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.CONCURRENCY</code>.
     */
    public String getConcurrency() {
        return (String) get(29);
    }

    /**
     * Setter for <code>KER.T_OBJECT.VISIBILITY</code>.
     */
    public void setVisibility(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.VISIBILITY</code>.
     */
    public String getVisibility() {
        return (String) get(30);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PERSISTENCE</code>.
     */
    public void setPersistence(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PERSISTENCE</code>.
     */
    public String getPersistence() {
        return (String) get(31);
    }

    /**
     * Setter for <code>KER.T_OBJECT.CARDINALITY</code>.
     */
    public void setCardinality(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.CARDINALITY</code>.
     */
    public String getCardinality() {
        return (String) get(32);
    }

    /**
     * Setter for <code>KER.T_OBJECT.GENTYPE</code>.
     */
    public void setGentype(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.GENTYPE</code>.
     */
    public String getGentype() {
        return (String) get(33);
    }

    /**
     * Setter for <code>KER.T_OBJECT.GENFILE</code>.
     */
    public void setGenfile(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.GENFILE</code>.
     */
    public String getGenfile() {
        return (String) get(34);
    }

    /**
     * Setter for <code>KER.T_OBJECT.HEADER1</code>.
     */
    public void setHeader1(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.HEADER1</code>.
     */
    public String getHeader1() {
        return (String) get(35);
    }

    /**
     * Setter for <code>KER.T_OBJECT.HEADER2</code>.
     */
    public void setHeader2(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.HEADER2</code>.
     */
    public String getHeader2() {
        return (String) get(36);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PHASE</code>.
     */
    public void setPhase(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PHASE</code>.
     */
    public String getPhase() {
        return (String) get(37);
    }

    /**
     * Setter for <code>KER.T_OBJECT.SCOPE</code>.
     */
    public void setScope(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.SCOPE</code>.
     */
    public String getScope() {
        return (String) get(38);
    }

    /**
     * Setter for <code>KER.T_OBJECT.GENOPTION</code>.
     */
    public void setGenoption(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.GENOPTION</code>.
     */
    public String getGenoption() {
        return (String) get(39);
    }

    /**
     * Setter for <code>KER.T_OBJECT.GENLINKS</code>.
     */
    public void setGenlinks(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.GENLINKS</code>.
     */
    public String getGenlinks() {
        return (String) get(40);
    }

    /**
     * Setter for <code>KER.T_OBJECT.CLASSIFIER</code>.
     */
    public void setClassifier(Long value) {
        set(41, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.CLASSIFIER</code>.
     */
    public Long getClassifier() {
        return (Long) get(41);
    }

    /**
     * Setter for <code>KER.T_OBJECT.EA_GUID</code>.
     */
    public void setEaGuid(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.EA_GUID</code>.
     */
    public String getEaGuid() {
        return (String) get(42);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PARENTID</code>.
     */
    public void setParentid(Long value) {
        set(43, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PARENTID</code>.
     */
    public Long getParentid() {
        return (Long) get(43);
    }

    /**
     * Setter for <code>KER.T_OBJECT.RUNSTATE</code>.
     */
    public void setRunstate(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.RUNSTATE</code>.
     */
    public String getRunstate() {
        return (String) get(44);
    }

    /**
     * Setter for <code>KER.T_OBJECT.CLASSIFIER_GUID</code>.
     */
    public void setClassifierGuid(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.CLASSIFIER_GUID</code>.
     */
    public String getClassifierGuid() {
        return (String) get(45);
    }

    /**
     * Setter for <code>KER.T_OBJECT.TPOS</code>.
     */
    public void setTpos(Long value) {
        set(46, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.TPOS</code>.
     */
    public Long getTpos() {
        return (Long) get(46);
    }

    /**
     * Setter for <code>KER.T_OBJECT.ISROOT</code>.
     */
    public void setIsroot(Long value) {
        set(47, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.ISROOT</code>.
     */
    public Long getIsroot() {
        return (Long) get(47);
    }

    /**
     * Setter for <code>KER.T_OBJECT.ISLEAF</code>.
     */
    public void setIsleaf(Long value) {
        set(48, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.ISLEAF</code>.
     */
    public Long getIsleaf() {
        return (Long) get(48);
    }

    /**
     * Setter for <code>KER.T_OBJECT.ISSPEC</code>.
     */
    public void setIsspec(Long value) {
        set(49, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.ISSPEC</code>.
     */
    public Long getIsspec() {
        return (Long) get(49);
    }

    /**
     * Setter for <code>KER.T_OBJECT.ISACTIVE</code>.
     */
    public void setIsactive(Long value) {
        set(50, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.ISACTIVE</code>.
     */
    public Long getIsactive() {
        return (Long) get(50);
    }

    /**
     * Setter for <code>KER.T_OBJECT.STATEFLAGS</code>.
     */
    public void setStateflags(String value) {
        set(51, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.STATEFLAGS</code>.
     */
    public String getStateflags() {
        return (String) get(51);
    }

    /**
     * Setter for <code>KER.T_OBJECT.PACKAGEFLAGS</code>.
     */
    public void setPackageflags(String value) {
        set(52, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.PACKAGEFLAGS</code>.
     */
    public String getPackageflags() {
        return (String) get(52);
    }

    /**
     * Setter for <code>KER.T_OBJECT.MULTIPLICITY</code>.
     */
    public void setMultiplicity(String value) {
        set(53, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.MULTIPLICITY</code>.
     */
    public String getMultiplicity() {
        return (String) get(53);
    }

    /**
     * Setter for <code>KER.T_OBJECT.STYLEEX</code>.
     */
    public void setStyleex(String value) {
        set(54, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.STYLEEX</code>.
     */
    public String getStyleex() {
        return (String) get(54);
    }

    /**
     * Setter for <code>KER.T_OBJECT.ACTIONFLAGS</code>.
     */
    public void setActionflags(String value) {
        set(55, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.ACTIONFLAGS</code>.
     */
    public String getActionflags() {
        return (String) get(55);
    }

    /**
     * Setter for <code>KER.T_OBJECT.EVENTFLAGS</code>.
     */
    public void setEventflags(String value) {
        set(56, value);
    }

    /**
     * Getter for <code>KER.T_OBJECT.EVENTFLAGS</code>.
     */
    public String getEventflags() {
        return (String) get(56);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TObjectRecord
     */
    public TObjectRecord() {
        super(TObject.T_OBJECT);
    }

    /**
     * Create a detached, initialised TObjectRecord
     */
    public TObjectRecord(Long objectId, String objectType, Long diagramId, String name, String alias, String author, String version, String note, Long packageId, String stereotype, Long ntype, String complexity, Long effort, String style, Long backcolor, Long borderstyle, Long borderwidth, Long fontcolor, Long bordercolor, Date createddate, Date modifieddate, String status, String abstract_, Long tagged, String pdata1, String pdata2, String pdata3, String pdata4, String pdata5, String concurrency, String visibility, String persistence, String cardinality, String gentype, String genfile, String header1, String header2, String phase, String scope, String genoption, String genlinks, Long classifier, String eaGuid, Long parentid, String runstate, String classifierGuid, Long tpos, Long isroot, Long isleaf, Long isspec, Long isactive, String stateflags, String packageflags, String multiplicity, String styleex, String actionflags, String eventflags) {
        super(TObject.T_OBJECT);

        set(0, objectId);
        set(1, objectType);
        set(2, diagramId);
        set(3, name);
        set(4, alias);
        set(5, author);
        set(6, version);
        set(7, note);
        set(8, packageId);
        set(9, stereotype);
        set(10, ntype);
        set(11, complexity);
        set(12, effort);
        set(13, style);
        set(14, backcolor);
        set(15, borderstyle);
        set(16, borderwidth);
        set(17, fontcolor);
        set(18, bordercolor);
        set(19, createddate);
        set(20, modifieddate);
        set(21, status);
        set(22, abstract_);
        set(23, tagged);
        set(24, pdata1);
        set(25, pdata2);
        set(26, pdata3);
        set(27, pdata4);
        set(28, pdata5);
        set(29, concurrency);
        set(30, visibility);
        set(31, persistence);
        set(32, cardinality);
        set(33, gentype);
        set(34, genfile);
        set(35, header1);
        set(36, header2);
        set(37, phase);
        set(38, scope);
        set(39, genoption);
        set(40, genlinks);
        set(41, classifier);
        set(42, eaGuid);
        set(43, parentid);
        set(44, runstate);
        set(45, classifierGuid);
        set(46, tpos);
        set(47, isroot);
        set(48, isleaf);
        set(49, isspec);
        set(50, isactive);
        set(51, stateflags);
        set(52, packageflags);
        set(53, multiplicity);
        set(54, styleex);
        set(55, actionflags);
        set(56, eventflags);
    }
}
